In [1]:
import pandas as pd
import scanpy as sc
import anndata
import os
import lamindb as ln

In [2]:
adata_from_zenodo = sc.read('SrivatsanTrapnell2020_sciplex3.h5ad', backup_url='https://zenodo.org/records/13350497/files/SrivatsanTrapnell2020_sciplex3.h5ad')

/usr/local/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████| 2.35G/2.35G [04:01<00:00, 10.5MB/s]

In [3]:
ln.connect('laminlabs/pertdata')
adata_from_lamin = ln.Artifact.get(key='scperturb/srivatsan20_sciplex3.h5ad').load()

→ connected lamindb: laminlabs/pertdata

In [4]:
adata_from_zenodo

AnnData object with n_obs × n_vars = 799317 × 110983
    obs: 'ncounts', 'well', 'plate', 'cell_line', 'replicate', 'time', 'dose_value', 'pathway_level_1', 'pathway_level_2', 'perturbation', 'target', 'pathway', 'dose_unit', 'celltype', 'disease', 'cancer', 'tissue_type', 'organism', 'perturbation_type'
    var: 'ensembl_id'

In [5]:
adata_from_lamin

AnnData object with n_obs × n_vars = 799317 × 58302
    obs: 'pert_target', 'pert_compound', 'pert_dose', 'pert_time', 'organism', 'cell_line', 'cell_type', 'disease', 'tissue_type', 'tissue', 'assay', 'suspension_type', 'donor_id', 'sex', 'self_reported_ethnicity', 'development_stage', 'pert_name', 'pert_type', 'ncounts', 'well', 'plate', 'replicate', 'time', 'dose_value', 'pathway_level_1', 'pathway_level_2', 'pathway', 'dose_unit', 'cancer'
    var: 'symbol'

In [6]:
adata_from_zenodo.obs[adata_from_zenodo.obs['well'].isna()]

,ncounts,well,plate,cell_line,replicate,time,dose_value,pathway_level_1,pathway_level_2,perturbation,target,pathway,dose_unit,celltype,disease,cancer,tissue_type,organism,perturbation_type
A01_E09_RT_BC_104_Lig_BC_76,1441,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
A01_E09_RT_BC_110_Lig_BC_98,1725,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
A01_E09_RT_BC_116_Lig_BC_25,1909,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
A01_E09_RT_BC_121_Lig_BC_282,571,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
A01_E09_RT_BC_123_Lig_BC_3,1461,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H12_F10_RT_BC_71_Lig_BC_352,1433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
H12_F10_RT_BC_74_Lig_BC_376,4205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
H12_F10_RT_BC_98_Lig_BC_174,844,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
H12_F10_RT_BC_98_Lig_BC_9,3048,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug
H12_F10_RT_BC_9_Lig_BC_4,726,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,nM,None,None,True,cell_line,human,drug

In [7]:
adata_from_lamin.obs[adata_from_lamin.obs['well'].isna()]

,pert_target,pert_compound,pert_dose,pert_time,organism,cell_line,cell_type,disease,tissue_type,tissue,assay,suspension_type,donor_id,sex,self_reported_ethnicity,development_stage,pert_name,pert_type,ncounts,well,plate,replicate,time,dose_value,pathway_level_1,pathway_level_2,pathway,dose_unit,cancer
A01_E09_RT_BC_104_Lig_BC_76,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,1441,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
A01_E09_RT_BC_110_Lig_BC_98,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,1725,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
A01_E09_RT_BC_116_Lig_BC_25,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,1909,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
A01_E09_RT_BC_121_Lig_BC_282,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,571,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
A01_E09_RT_BC_123_Lig_BC_3,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,1461,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
H12_F10_RT_BC_71_Lig_BC_352,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,1433,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
H12_F10_RT_BC_74_Lig_BC_376,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,4205,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
H12_F10_RT_BC_98_Lig_BC_174,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,844,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
H12_F10_RT_BC_98_Lig_BC_9,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,3048,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True
H12_F10_RT_BC_9_Lig_BC_4,NaN,NaN,0.0nM,24h,human,NaN,NaN,NaN,cell culture,NaN,sci-Plex,nucleus,unknown,NaN,NaN,unknown,NaN,compound,726,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,nM,True

In [9]:
percentage = (adata_from_zenodo.obs[adata_from_zenodo.obs['well'].isna()].shape[0]/adata_from_zenodo.obs.shape[0]) * 100
print(f'Rows with missed values {percentage}%')

Rows with missed values 4.569150912591625%

In [10]:
percentage = (adata_from_lamin.obs[adata_from_lamin.obs['well'].isna()].shape[0]/adata_from_lamin.obs.shape[0]) * 100
print(f'Rows with missed values {percentage}%')

Rows with missed values 4.569150912591625%