# level 5 L1000 annotation

In [1]:
from __future__ import annotations

from typing import Optional, Iterable
from pathlib import Path
import gzip
import shutil
import subprocess
import numpy as np
import pandas as pd
import scipy.sparse as sp
import anndata as ad

In [20]:
import sys
sys.path.append("./op3_v2")

from src.utils.parsing_utils import *
from src.pseudobulking.common.pubchem import lookup_pubchem_cids
from src.pseudobulking.datasets.l1000.pubchem_imputation import pubchem_mapping_l1000
from src.pseudobulking.datasets.l1000.cellosaurus_annotation import annotate_cell_lines
from src.pseudobulking.datasets.l1000.donor_metadata_annotation import fetch_donor_info_from_cellosaurus
from src.pseudobulking.datasets.l1000.gene_annotation import fetch_ensg_ids
from src.pseudobulking.datasets.l1000.assembling import *

In [27]:
def _read_table(path: Path, **kwargs) -> pd.DataFrame:
    """
    Read a table file, handling gzipped files automatically.
    
    Attempts to read the file at the specified path. If not found, looks for
    a gzipped version (.gz) and reads it instead.
    
    Parameters
    ----------
    path : Path
        Path to the table file (CSV format)
    **kwargs
        Additional arguments passed to pd.read_csv()
        
    Returns
    -------
    pd.DataFrame
        Loaded table data
        
    Raises
    ------
    FileNotFoundError
        If neither the file nor its gzipped version exists
    """
    if not path.exists():
        gz = path.with_suffix(path.suffix + ".gz")
        if gz.exists():
            with gzip.open(gz, "rt") as fh:
                df = pd.read_csv(fh, **kwargs)
        else:
            raise FileNotFoundError(path)
    else:
        df = pd.read_csv(path, **kwargs)
    df.columns = (
        df.columns
        .str.strip()
        .str.replace(" ", "_", regex=False)
        .str.replace("-", "_", regex=False)
        .str.lower()
    )
    return df

In [39]:
def download_l1000_files(data_root: Optional[str] = None, dataset: str = "l1000_phase1", skip_existing: bool = True) -> None:
    """
    Download L1000 Level 3 data files from GEO and CLUE.
    
    Downloads all required L1000 Level 3 files including:
    - GCTX expression file (48.8 GB)
    - Instance metadata
    - Cell line metadata
    - Perturbagen metadata
    - Gene annotations
    
    Parameters
    ----------
    data_root : str, optional
        Root directory for data files. If None, uses default from define_paths()
    dataset : str, default="l1000_phase1"
        Dataset name: "l1000_phase1" or "l1000_phase2"
    skip_existing : bool, default=True
        If True, skips downloading files that already exist
        
    Raises
    ------
    subprocess.CalledProcessError
        If download command fails
    """
    if data_root is None:
        paths = define_paths(dataset=dataset)
        data_root = Path(paths["level5_gctx"]).parent
    else:
        data_root = Path(data_root)
    
    data_root.mkdir(parents=True, exist_ok=True)
    
    manifest_df = get_download_manifest(data_root, dataset=dataset)
    
    logger.info(f"Downloading L1000 Level 3 files to: {data_root}")
    
    for _, row in manifest_df.iterrows():
        file_path = row["path"]
        
        if skip_existing and file_path.exists():
            logger.info(f"  {row['file']} already exists, skipping")
            continue
        
        logger.info(f"  Downloading {row['file']} ({row['size']})...")
        cmd = f"curl -L '{row['url']}' -o {file_path}"
        
        try:
            subprocess.run(cmd, shell=True, check=True)
            logger.info(f"    Downloaded {row['file']}")
        except subprocess.CalledProcessError as e:
            logger.error(f"    Failed to download {row['file']}: {e}")
            raise
    
    logger.info("All downloads complete")

def decompress_l1000_files(data_root: Optional[str] = None, dataset: str = "l1000_phase1") -> None:
    """
    Decompress gzipped L1000 data files.
    
    Decompresses all .gz files in the data directory, including the large GCTX
    expression file. The GCTX decompression may take several minutes.
    
    Parameters
    ----------
    data_root : str, optional
        Root directory containing compressed files. If None, uses default from define_paths()
    dataset : str, default="l1000_phase1"
        Dataset name: "l1000_phase1" or "l1000_phase2"
        
    Raises
    ------
    FileNotFoundError
        If compressed files are not found
    """
    if data_root is None:
        paths = define_paths(dataset=dataset)
        data_root = Path(paths["level5_gctx"]).parent
    else:
        data_root = Path(data_root)
    
    paths = define_paths(str(data_root), dataset=dataset)
    to_decompress = []
    already_done = []
    
    for key, path in paths.items():
        if key.endswith("_gz"):
            continue
        
        path = Path(path)
        if not path.suffix == ".gz":
            gz_candidate = path.with_suffix(path.suffix + ".gz")
            if gz_candidate.exists() and not path.exists():
                to_decompress.append((key, gz_candidate, path))
            elif path.exists():
                already_done.append((key, path))
    
    if already_done:
        logger.info(f"{len(already_done)} file(s) already decompressed")
        for key, path in already_done:
            logger.info(f"  - {key}: {path.name}")
    
    if to_decompress:
        logger.info(f"Decompressing {len(to_decompress)} file(s)...")
        for key, gz_path, target_path in to_decompress:
            logger.info(f"  - {key}: {gz_path.name} -> {target_path.name}")
            if "gctx" in key.lower():
                logger.info("    (GCTX is large, this may take a few minutes...)")
            
            with gzip.open(gz_path, "rb") as src, open(target_path, "wb") as dst:
                shutil.copyfileobj(src, dst)
            logger.info(f"    Done")
        
        logger.info(f"All {len(to_decompress)} file(s) successfully decompressed")
    else:
        if not already_done:
            logger.warning("No compressed files found. Download them first using download_l1000_files()")
        else:
            logger.info("All files are already decompressed")


def get_download_manifest(data_root: Path, dataset: str = "l1000_phase1") -> pd.DataFrame:
    """
    Get manifest of L1000 Level 3 files to download.
    
    Returns a DataFrame with download information for all required L1000 Level 3
    files from GEO and CLUE resources.
    
    Parameters
    ----------
    data_root : Path
        Root directory where files will be downloaded
        
    Returns
    -------
    pd.DataFrame
        Download manifest with columns: file, kind, size, url, path, notes, curl_example
    """
    if dataset == "l1000_phase1":
        download_manifest = [
            {
                "file": "GSE92742_Broad_LINCS_Level5_COMPZ.MODZ_n473647x12328.gctx.gz",
                "kind": "expression",
                "size": "...",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE92nnn/GSE92742/suppl/GSE92742_Broad_LINCS_Level5_COMPZ.MODZ_n473647x12328.gctx.gz",
                "notes": "Processed expression"
            },
            {
                "file": "GSE92742_Broad_LINCS_sig_info.txt.gz", 
                "kind": "metadata", 
                "size": "~10.6 MB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE92nnn/GSE92742/suppl/GSE92742_Broad_LINCS_sig_info.txt.gz",
                "notes": "Signatures information"
            },
            {
                "file": "GSE92742_Broad_LINCS_inst_info.txt.gz",
                "kind": "metadata",
                "size": "~150 MB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE92nnn/GSE92742/suppl/GSE92742_Broad_LINCS_inst_info.txt.gz",
                "notes": "Instance-level annotations"
            },
            {
                "file": "GSE92742_Broad_LINCS_cell_info.txt.gz",
                "kind": "metadata",
                "size": "<10 KB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE92nnn/GSE92742/suppl/GSE92742_Broad_LINCS_cell_info.txt.gz",
                "notes": "Cell line annotations"
            },
            {
                "file": "GSE92742_Broad_LINCS_pert_info.txt.gz",
                "kind": "metadata",
                "size": "~5 MB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE92nnn/GSE92742/suppl/GSE92742_Broad_LINCS_pert_info.txt.gz",
                "notes": "Perturbagen annotations"
            },
            {
                "file": "GSE92742_Broad_LINCS_gene_info.txt.gz",
                "kind": "metadata",
                "size": "<1 MB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE92nnn/GSE92742/suppl/GSE92742_Broad_LINCS_gene_info.txt.gz",
                "notes": "Gene annotations"
            }
        ]
    elif dataset == "l1000_phase2":
        download_manifest = [
                {
                "file": "GSE70138_Broad_LINCS_Level5_COMPZ_n118050x12328_2017-03-06.gctx.gz",
                "kind": "expression",
                "size": "12.6 GB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE70nnn/GSE70138/suppl/GSE70138_Broad_LINCS_Level5_COMPZ_n118050x12328_2017-03-06.gctx.gz",
                "notes": "Raw epsilon (landmark genes)"
            },
               {
                "file": "GSE70138_Broad_LINCS_sig_info_2017-03-06.txt.gz", 
                "kind": "metadata", 
                "size": "~1.9 MB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE70nnn/GSE70138/suppl/GSE70138_Broad_LINCS_sig_info_2017-03-06.txt.gz",
                "notes": "Signatures information"
            },
            {
                "file": "GSE70138_Broad_LINCS_inst_info_2017-03-06.txt.gz",
                "kind": "metadata",
                "size": "~150 MB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE70nnn/GSE70138/suppl/GSE70138_Broad_LINCS_inst_info_2017-03-06.txt.gz",
                "notes": "Instance-level annotations"
            },
            {
                "file": "GSE70138_Broad_LINCS_cell_info_2017-04-28.txt.gz",
                "kind": "metadata",
                "size": "<10 KB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE70nnn/GSE70138/suppl/GSE70138_Broad_LINCS_cell_info_2017-04-28.txt.gz",
                "notes": "Cell line annotations"
            },
            {
                "file": "GSE70138_Broad_LINCS_pert_info.txt.gz",
                "kind": "metadata",
                "size": "~5 MB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE70nnn/GSE70138/suppl/GSE70138_Broad_LINCS_pert_info.txt.gz",
                "notes": "Perturbagen metadata"
            },
            {
                "file": "GSE70138_Broad_LINCS_gene_info_2017-03-06.txt.gz",
                "kind": "metadata",
                "size": "~210 KB",
                "url": "https://ftp.ncbi.nlm.nih.gov/geo/series/GSE70nnn/GSE70138/suppl/GSE70138_Broad_LINCS_gene_info_2017-03-06.txt.gz",
                "notes": "Landmark gene annotations"
            }
            
        ]
    else:
        raise ValueError(f"Invalid dataset: {dataset}")
    
    manifest_df = pd.DataFrame(download_manifest)
    manifest_df["path"] = manifest_df["file"].apply(lambda f: data_root / f)
    manifest_df["curl_example"] = manifest_df.apply(
        lambda row: f"curl -L '{row['url']}' -o {row['path']}",
        axis=1
    )
    
    return manifest_df

def check_l1000_files(data_root: Optional[str] = None, dataset: str = "l1000_phase1") -> dict:
    """
    Check status of L1000 data files.
    
    Checks which files are missing, compressed, or ready to use.
    
    Parameters
    ----------
    data_root : str, optional
        Root directory to check. If None, uses default from define_paths()
    dataset : str, default="l1000_phase1"
        Dataset name: "l1000_phase1" or "l1000_phase2"
        
    Returns
    -------
    dict
        Dictionary with keys 'missing', 'compressed', 'ready' containing lists of
        (key, path) tuples for each category
    """
    if data_root is None:
        paths = define_paths(dataset=dataset)
        data_root = Path(paths["sig"]).parent
    else:
        data_root = Path(data_root)
    
    paths = define_paths(str(data_root), dataset=dataset)
    
    missing = []
    compressed = []
    ready = []
    
    for key, path in paths.items():
        if key.endswith("_gz"):
            continue
        
        # Skip pubchem cache JSON files
        path_str = str(path)
        if "pubchem_cache" in key.lower() and path_str.endswith(".json"):
            continue

        # Skip hgnc cache JSON files
        if "hgnc_cache" in key.lower() and path_str.endswith(".json"):
            continue
        
        path = Path(path)
        if path.suffix == ".gz":
            if not path.exists():
                missing.append((key, path))
        else:
            gz_candidate = path.with_suffix(path.suffix + ".gz")
            if path.exists():
                ready.append((key, path))
            elif gz_candidate.exists():
                compressed.append((key, gz_candidate))
            else:
                missing.append((key, path))
    
    # Log status
    if missing:
        logger.warning(f"{len(missing)} file(s) missing:")
        for key, path in missing:
            logger.warning(f"  - {key}: {path.name}")
        logger.info("  Run download_l1000_files() to download them")
    else:
        logger.info("All required files are present")
    
    if compressed:
        logger.warning(f"{len(compressed)} file(s) still compressed:")
        for key, path in compressed:
            logger.warning(f"  - {key}: {path.name}")
        logger.info("  Run decompress_l1000_files() to extract them")
    else:
        if not missing:
            logger.info("All files are uncompressed and ready to use")
    
    return {
        "missing": missing,
        "compressed": compressed,
        "ready": ready
    }


def standardize_sig(sig: pd.DataFrame) -> pd.DataFrame:
    """
    Standardize signature metadata.
    
    This function standardizes the signature ID column to 'lincs_sig_id' and adds plate
    information if missing by parsing the signature ID.
    
    Parameters
    ----------
    sig : pd.DataFrame
        Instance metadata with sig_id, sample_id, or distil_id column
        
    Returns
    -------
    pd.DataFrame
        Standardized dataframe with 'lincs_sig_id' as index and column, and 'det_plate' column added if missing
    """
    df = sig.copy()
    
    # Find ID column
    for id_col in ["sig_id", "sample_id", "distil_id"]:
        if id_col in df.columns:
            df = df.rename(columns={id_col: "lincs_sig_id"})
            break
    else:
        raise KeyError("sig info missing sig_id/sample_id/distil_id")
    
    # Add plate info if missing
    #if 'det_plate' not in df.columns:
    #    df['det_plate'] = df['lincs_sig_id'].str.split(':').str[0]
    
    return df.set_index("lincs_sig_id", drop=False)








def build_obs_dataframe(sig: pd.DataFrame, dataset: str = "l1000_phase1") -> pd.DataFrame:
    """
    Build standardized .obs dataframe from signature metadata.
    Sticked to https://lamin.ai/laminlabs/pertdata/transform/REAvqqdo3sbH0000
    
    Parameters
    ----------
    sig : pd.DataFrame
        Instance metadata dataframe with LINCS information
        
    Returns
    -------
    pd.DataFrame
        Standardized obs dataframe with pseudobulk schema
    """
    obs = pd.DataFrame(index=sig.index)
    
    # Copy identifier columns
    for extra_id in ("lincs_sig_id", "distil_id", "inst_id", "sample_id", "sig_id"):
        if extra_id in sig.columns:
            obs[extra_id] = sig[extra_id].astype("string")
    
    # Map perturbation types to standard schema
    PERT_TYPE_MAP = {
        "trt_cp": "compound",
        "trt_lig": "biologic",
        "trt_sh": "genetic",
        "trt_oe": "genetic",
        "trt_oe.mut": "genetic",
        "trt_xpr": "genetic",
        "ctl_vehicle": "compound",
        "trt_poscon": "compound",
        "ctl_vector": "genetic",
        "ctl_untrt": "biologic"
        
    }

    
    # Build standard obs columns
    obs["plate"] = sig.get("det_plate", None)
    obs["well"] = sig.get("rna_well", sig.get("det_well", None))
    obs["cell_type"] = sig.get("cellinfo_cell_id_mixed", sig.get("cell_id", None)).fillna(sig.get("cell_id", None))
    obs["perturbagen"] = sig.get("pert_iname", None)
    obs["pert_type"] = sig["pert_type"].map(PERT_TYPE_MAP)
    obs["is_control"] = sig["pert_type"].str.startswith("ctl")
    obs["pert_dose_uM"] = sig["pert_dose_um"].astype(float)
    obs.loc[(obs['perturbagen']=='DMSO') & (obs['is_control']==True), 'pert_dose_uM'] = 0
    obs['pert_dose'] = sig['pert_dose'].astype(str) + ' ' + sig['pert_dose_unit'].astype(str)
    obs["pert_time_h"] = sig["pert_time_h"].astype(float)
    obs["suspension_type"] = "cell"
    obs["tissue"] = sig.get("cellinfo_primary_site", "unknown")
    obs["tissue_type"] = "cell culture"
    obs["disease"] = sig.get("cellinfo_subtype", "unknown")
    obs["library"] = None
    obs["stimulation"] = None
    obs["guide"] = None

    if dataset == "l1000_phase1":
        obs["dataset"] = "LINCS_phase1_level3_epsilon"
    elif dataset == "l1000_phase2":
        obs["dataset"] = "LINCS_phase2_level3"
    else:
        raise ValueError(f"Invalid dataset: {dataset}")

    obs["assay"] = "L1000 mRNA profiling assay"
    obs["development_stage"] = sig.apply(build_development_stage, axis=1)
    obs["organism"] = "human"
    if 'cellinfo_donor_sex' in sig.columns:
        obs["sex"] = sig["cellinfo_donor_sex"].map({"M": "male", "F": "female"})
    else:
        obs["sex"] = "unknown"
        
    obs["self_reported_ethnicity"] = sig.get("cellinfo_donor_ethnicity", "unknown")
    if 'pubchem_cid' in sig.columns:
        sig['pubchem_cid'] = pd.to_numeric(sig['pubchem_cid'], errors='coerce').fillna(-666).astype('int64')
    obs["pubchem_cid"] = sig.get("pubchem_cid", None)
    obs["psbulk_cells"] = None
    obs["psbulk_counts"] = None
    
    # Add metadata columns
    obs["lincs_sig_id"] = sig.index.astype("string")
    obs["source_gctx"] = sig["source_gctx"].astype("string")
    
    # Create composite sample_id
    obs["sample_id"] = (
        obs["plate"].astype(str).str.replace(" ", "", regex=False) + "_" +
        obs["well"].astype(str).str.replace(" ", "", regex=False) + "_" +
        obs["perturbagen"].astype(str).str.replace(" ", "_", regex=False) + "_" +
        obs["cell_type"].astype(str).str.replace(" ", "_", regex=False)
    )

    obs["pert_type_init"] = sig["pert_type_pert"].copy()
    # Clean up missing values and duplicates
    obs = obs.replace({-666: None, '-666': None, 'None': None, 'nan': None, '<NA>': None})
    #obs = obs[~obs["sample_id"].duplicated(keep="first")]
    obs = obs.set_index("sig_id", drop=True)
    obs = materialize_string_columns(obs)
    return obs



def define_obs_schema() -> list:
    """
    Define the strict obs schema for L1000 pseudobulk data.
    
    Returns
    -------
    list
        List of tuples defining the schema: (column_name, dtype, description)
    """
    return [
        ("sample_id", "category", "ID of the observation: plate + well + cell_type + perturbagen"),
        ("plate", "category", "Assay plate identifier (det_plate)"),
        ("well", "category", "Well ID on the RNA plate (rna_well)"),
        ("cell_type", "category", "Cell line / cell_id"),
        ("perturbagen", "category", "Human-readable perturbagen label"),
        ("pert_type", "category", "Perturbation class"),
        ("is_control", "category", "True/False for controls"),
        ("pert_dose_uM", "float64", "Dose in micromolar"),
        ("pert_time_h", "float64", "Exposure time in hours"),
        ("suspension_type", "category", "Growth pattern"),
        ("tissue", "category", "Primary tissue/site"),
        ("tissue_type", "category", "Sample type"),
        ("disease", "category", "Disease/subtype"),
        ("library", "category", "Library/release"),
        ("stimulation", "category", "High-level stimulus"),
        ("guide", "category", "A guide RNA directs the CRISPR system"),
        ("dataset", "category", "Dataset label"),
        ("assay", "category", "Assay label"),
        ("development_stage", "category", "Derived from donor age"),
        ("organism", "category", "Organism"),
        ("sex", "category", "Donor sex"),
        ("self_reported_ethnicity", "category", "Donor ethnicity"),
        ("pubchem_cid", "category", "PubChem CID"),
        ("psbulk_cells", "int64", "Total #cells contributing (if no info - then -666)"),
        ("psbulk_counts", "int64", "Total #counts contributing (if no info - then -666)"),
        ("distil_id", "category", "distil_id"),
        ("sig_id", "category", "signature id"),
        ("pert_type_init", "category", "initial perturbation type"),
        ("pert_dose", "category", "initial perturbation type")
    ]


def define_paths(data_root: Optional[str] = None, dataset: str = "l1000_phase1") -> dict:
    """
    Define file paths for L1000 Level 3 data.
    
    Parameters
    ----------
    data_root : str, optional
        Root directory containing L1000 data files.
        Defaults to './lincs_data'
        
    Returns
    -------
    dict
        Dictionary mapping file identifiers to Path objects
    """
    if data_root is None:
        data_root = './lincs_data'
    
    data_root = Path(data_root)
    processed_dir = data_root / "processed"
    processed_dir.mkdir(exist_ok=True)
    
    if dataset == "l1000_phase1":
        return {
                "level5_gctx": data_root / "GSE92742_Broad_LINCS_Level5_COMPZ.MODZ_n473647x12328.gctx",
                "level5_gctx_gz": data_root / "GSE92742_Broad_LINCS_Level5_COMPZ.MODZ_n473647x12328.gctx.gz",
                "instinfo": data_root / "GSE92742_Broad_LINCS_inst_info.txt",
                "siginfo": data_root / "GSE92742_Broad_LINCS_sig_info.txt",
                "cellinfo": data_root / "GSE92742_Broad_LINCS_cell_info.txt",
                "pert_info": data_root / "GSE92742_Broad_LINCS_pert_info.txt",
                "geneinfo": data_root / "GSE92742_Broad_LINCS_gene_info.txt",
                "pubchem_cache": processed_dir / "pubchem_cache.json",
                "hgnc_cache": processed_dir / "hgnc_cache.json"
                
        }
    elif dataset == "l1000_phase2":
        return {
                "level5_gctx": data_root / "GSE70138_Broad_LINCS_Level5_COMPZ_n118050x12328_2017-03-06.gctx",
                "level5_gctx_gz": data_root / "GSE70138_Broad_LINCS_Level5_COMPZ_n118050x12328_2017-03-06.gctx.gz",
                "instinfo": data_root / "GSE70138_Broad_LINCS_inst_info_2017-03-06.txt",
                "siginfo": data_root / "GSE70138_Broad_LINCS_sig_info_2017-03-06.txt",
                "cellinfo": data_root / "GSE70138_Broad_LINCS_cell_info_2017-04-28.txt",
                "pert_info": data_root / "GSE70138_Broad_LINCS_pert_info.txt",
                "geneinfo": data_root / "GSE70138_Broad_LINCS_gene_info_2017-03-06.txt",
                "pubchem_cache": processed_dir / "pubchem_cache.json",
                "hgnc_cache": processed_dir / "hgnc_cache.json",
        }
    else:
        raise ValueError(f"Invalid dataset: {dataset}")

def add_alternative_identifiers(sig_raw: pd.DataFrame) -> pd.DataFrame:
    """
    Standardize signature metadata and add alternative identifier columns.
    
    This function standardizes the signature ID column and preserves alternative
    identifiers (distil_id, sig_id, sample_id, sig_id) for cross-referencing.
    
    Parameters
    ----------
    sig_raw : pd.DataFrame
        Raw signature/sample metadata
        
    Returns
    -------
    pd.DataFrame
        Instance metadata with standardized lincs_sig_id index
        and additional identifier columns
    """
    logger.info('  Processing signature metadata')
    sig = standardize_sig(sig_raw)
    
    # Keep alternative identifier columns
    sig_raw_tmp = sig_raw.copy()
    if 'lincs_sig_id' not in sig_raw_tmp.columns:
        if 'sample_id' in sig_raw_tmp.columns:
            sig_raw_tmp['lincs_sig_id'] = sig_raw_tmp['sample_id']
        elif 'sig_id' in sig_raw_tmp.columns:
            sig_raw_tmp['lincs_sig_id'] = sig_raw_tmp['sig_id']
        else:
            raise ValueError("signature metadata must have lincs_sig_id, sample_id, or sig_id column")
    
    sig_raw_indexed = sig_raw_tmp.set_index("lincs_sig_id", drop=False)
    
    for extra_id in ("distil_id", "sig_id", "sample_id", "sig_id"):
        if extra_id in sig_raw_indexed.columns:
            sig[extra_id] = sig_raw_indexed.loc[sig.index, extra_id].astype("string")
    
    return sig





def enrich_sig_metadata(sig: pd.DataFrame, 
                            cellinfo: pd.DataFrame,
                            pert_raw: pd.DataFrame) -> pd.DataFrame:
    """
    Enrich instance metadata by merging with cell and perturbation info.
    
    Parameters
    ----------
    sig : pd.DataFrame
        Processed signature metadata
    cellinfo : pd.DataFrame
        Cell line information
    pert_raw : pd.DataFrame
        Perturbation information
        
    Returns
    -------
    pd.DataFrame
        Enriched signature metadata with merged information
    """
    def fix_cell_line_annotation(df: pd.DataFrame) -> pd.DataFrame:
        mask = df['cell_id'] == 'SNUC4'
        df.loc[mask, 'cellinfo_subtype'] = 'colon adenocarcinoma'
        df.loc[mask, 'cellinfo_donor_age'] = '35'
        df.loc[mask, 'cellinfo_donor_sex'] = 'M'
        df.loc[mask, 'cellinfo_donor_ethnicity'] = 'Korean'
        df.loc[mask, 'cellinfo_cellosaurus_id'] = 'CVCL_5111'
        df.loc[mask, 'cellinfo_cell_id_mixed'] = 'CVCL_5111'
        return df
    
    pert_cols = ["pert_id", "pert_iname", "pert_type", "pubchem_cid"]
    sig = sig.merge(cellinfo, how="left", left_on="cell_id", right_index=True)    
    sig = sig.merge(pert_raw[pert_cols].drop_duplicates("pert_id"), 
                     how="left", on="pert_id", suffixes=("", "_pert"))

    sig = fix_cell_line_annotation(sig).copy()
    
    return sig


def process_sig_metadata(sig_raw: pd.DataFrame,
                            cellinfo: pd.DataFrame,
                            pert_raw: pd.DataFrame,
                            config: dict,
                            paths: dict,
                            max_samples: int = 1000) -> pd.DataFrame:
    """
    Process signature metadata through complete pipeline.
    
    This function handles the full signature metadata processing pipeline:
    1. Add alternative identifiers (distil_id, sig_id, sample_id, sig_id)
    2. Enrich with cell and perturbation information
    3. Standardize dose units to micromolar
    4. Standardize time units to hours
    5. Apply filters (perturbation types, controls, subsampling)
    6. Add source file information
    
    Parameters
    ----------
    sig_raw : pd.DataFrame
        Raw signature/sample metadata
    cellinfo : pd.DataFrame
        Cell line information
    pert_raw : pd.DataFrame
        Perturbation information
    config : dict
        Configuration with filter settings
    paths : dict
        Dictionary of file paths
        
    Returns
    -------
    pd.DataFrame
        Fully processed and filtered signature metadata
    """
    sig = add_alternative_identifiers(sig_raw)
    sig = enrich_sig_metadata(sig, cellinfo, pert_raw)
    sig = standardize_dose(sig)
    sig = standardize_time(sig)
    
    # Apply filters
    if config["perturbation_types_to_keep"] is not None:
        sig = sig[sig["pert_type"].isin(config["perturbation_types_to_keep"])]

    if config["control"] is not None:
        sig = sig[(sig['pert_type'].str.startswith('ctl') & sig['pert_iname'].isin(config['control'])) |
                    (~sig['pert_type'].str.startswith('ctl'))]

    cell_ids_with_controls = set(sig[sig['pert_type'].str.startswith('ctl')]['cell_id'].unique())
    cell_ids_with_compounds = set(sig[~sig['pert_type'].str.startswith('ctl')]['cell_id'].unique())
    valid_cell_ids = cell_ids_with_controls & cell_ids_with_compounds
    if len(valid_cell_ids) == 0:
        raise ValueError("No cell lines found with both controls and compounds")

    sig = sig[sig['cell_id'].isin(valid_cell_ids)].copy()

    if config["subsampling"]:
        sig = sig.sample(max_samples, random_state=0)
    
    # Add source file information
    sig["source_gctx"] = str(paths["level5_gctx"])
    
    return sig


def load_metadata_tables(paths: dict) -> tuple:
    """
    Load L1000 metadata tables from files.
    
    Parameters
    ----------
    paths : dict
        Dictionary of file paths from define_paths()
        
    Returns
    -------
    tuple
        (sig_raw, cellinfo_raw, pert_raw, geneinfo)
        - sig_raw: Instance/sample information
        - cellinfo_raw: Cell line information
        - pert_raw: Perturbation information
        - geneinfo: Gene annotations (Level 3)
    """
    logger.info('  Loading metadata tables')
    inst_raw = _read_table(paths["instinfo"], sep="\t", low_memory=False)
    sig_raw = _read_table(paths["siginfo"], sep="\t", low_memory=False)
    cellinfo_raw = _read_table(paths["cellinfo"], sep="\t")
    pert_raw = _read_table(paths["pert_info"], sep="\t")
    geneinfo = _read_table(paths["geneinfo"], sep="\t")
    
    
    # Log loaded table sizes
    logger.info(f"    Loaded {len(sig_raw):,} signatures")
    logger.info(f"    Loaded {len(cellinfo_raw):,} cell lines")
    logger.info(f"    Loaded {len(pert_raw):,} perturbations")
    logger.info(f"    Loaded {len(geneinfo):,} genes")
    
    return inst_raw, sig_raw, cellinfo_raw, pert_raw, geneinfo

In [29]:
config = {
        'data_root': './lincs_data',
        'output_file': 'level5_phase1_not_filtered.h5ad',
        'perturbation_types_to_keep': None,
        'control': None,
        'full_gene_matrix': False,
        'subsampling': False,
        'annotate_pubchem': True,
        'download_if_missing': True,
        'dataset': 'l1000_phase1',
    }

In [30]:
data_root = './lincs_data'
padata = ad.AnnData()

In [31]:
logger.info('Applying L1000-specific processing')

if not HAS_CMAPPY:
    raise ImportError("cmapPy is required for L1000 processing. Install via: pip install cmapPy")

# Build configuration
CONFIG = build_config(config)
download_if_missing = CONFIG.get("download_if_missing", True)

# Define file paths
PATHS = define_paths(data_root, dataset=CONFIG.get("dataset"))

2026-01-29 19:54:26 | [INFO] Applying L1000-specific processing

In [32]:
# Check data availability and download if needed
if download_if_missing:
        logger.info("Checking data availability...")
        status = check_l1000_files(data_root, dataset=CONFIG.get("dataset"))
        
        if status['missing']:
            logger.info(f"Downloading {len(status['missing'])} missing file(s)...")
            download_l1000_files(data_root, dataset=CONFIG.get("dataset"), skip_existing=True)
            status = check_l1000_files(data_root, dataset=CONFIG.get("dataset"))
        
        
        if status['compressed']:
            logger.info(f"Decompressing {len(status['compressed'])} compressed file(s)...")
            decompress_l1000_files(data_root, dataset=CONFIG.get("dataset"))
        
        # Verify all files are ready
        final_status = check_l1000_files(data_root, dataset=CONFIG.get("dataset"))
        if final_status['missing'] or final_status['compressed']:
            raise FileNotFoundError(
                f"Required L1000 data files are still missing or compressed after download attempt. "
                f"Missing: {len(final_status['missing'])}, Compressed: {len(final_status['compressed'])}"
            )
        logger.info("All required data files are available")

FULL_GENE_MATRIX = CONFIG["full_gene_matrix"]

2026-01-29 19:54:26 | [INFO] Checking data availability...
2026-01-29 19:54:26 | [INFO] All required files are present
2026-01-29 19:54:26 | [INFO] All files are uncompressed and ready to use
2026-01-29 19:54:26 | [INFO] All required files are present
2026-01-29 19:54:26 | [INFO] All files are uncompressed and ready to use
2026-01-29 19:54:26 | [INFO] All required data files are available

In [33]:
# Load metadata tables
inst_raw, sig_raw, cellinfo_raw, pert_raw, geneinfo = load_metadata_tables(PATHS)

2026-01-29 19:54:27 | [INFO]   Loading metadata tables
2026-01-29 19:54:40 | [INFO]     Loaded 473,647 signatures
2026-01-29 19:54:40 | [INFO]     Loaded 98 cell lines
2026-01-29 19:54:40 | [INFO]     Loaded 51,383 perturbations
2026-01-29 19:54:40 | [INFO]     Loaded 12,328 genes

In [34]:
NAME_TO_CVCL = {
        "HA1E": "CVCL_VU89",
        "HEK293T": "CVCL_0063",
        "HS27A": "CVCL_3719",
        "FIBRNPC": "CVCL_UK07",
        "U266": "CVCL_0566",
        "HUES3": "CVCL_B161",
        "HUVEC": "CVCL_2959",
        "H1299": "CVCL_0060",
        "HL60": "CVCL_0002",
        "SKBR3": "CVCL_0033",
        "ASC": "CVCL_U602"
    }

In [35]:
cellinfo = process_cellinfo(cellinfo_raw)

2026-01-29 19:55:07 | [INFO] Annotating cell lines with Cellosaurus IDs
2026-01-29 19:55:08 | [INFO] Annotating 81 unique cell types
2026-01-29 19:55:14 | [INFO] Processed 10/81 cell types (10 mapped so far)
2026-01-29 19:55:20 | [INFO] Processed 20/81 cell types (20 mapped so far)
2026-01-29 19:55:25 | [INFO] Processed 30/81 cell types (30 mapped so far)
2026-01-29 19:55:30 | [INFO] Processed 40/81 cell types (40 mapped so far)
2026-01-29 19:55:35 | [INFO] Processed 50/81 cell types (49 mapped so far)
2026-01-29 19:55:39 | [INFO] Processed 60/81 cell types (59 mapped so far)
2026-01-29 19:55:44 | [INFO] Processed 70/81 cell types (69 mapped so far)
2026-01-29 19:55:50 | [INFO] Processed 80/81 cell types (74 mapped so far)
2026-01-29 19:55:50 | [INFO] Completed: 74/81 cell types successfully mapped to Cellosaurus IDs
2026-01-29 19:55:51 | [INFO] Fetching donor information from Cellosaurus API
2026-01-29 19:55:51 | [INFO] Fetching donor information for 74 unique Cellosaurus IDs
2026-01-29 19:55:52 | [INFO] Processed 10/74 Cellosaurus IDs (8 with donor info)
2026-01-29 19:55:54 | [INFO] Processed 20/74 Cellosaurus IDs (16 with donor info)
2026-01-29 19:55:56 | [INFO] Processed 30/74 Cellosaurus IDs (25 with donor info)
2026-01-29 19:55:57 | [INFO] Processed 40/74 Cellosaurus IDs (34 with donor info)
2026-01-29 19:55:59 | [INFO] Processed 50/74 Cellosaurus IDs (43 with donor info)
2026-01-29 19:56:00 | [INFO] Processed 60/74 Cellosaurus IDs (53 with donor info)
2026-01-29 19:56:02 | [INFO] Processed 70/74 Cellosaurus IDs (63 with donor info)
2026-01-29 19:56:02 | [INFO] Completed: 64/74 IDs have donor information

In [36]:
# Process perturbation metadata
pert_raw = process_pert_metadata(pert_raw, sig_raw)

In [37]:
# Annotate compounds with PubChem CIDs (optional)
if CONFIG.get("annotate_pubchem", False):
    logger.info("Mapping compounds to PubChem CIDs")
    pert_raw = annotate_pubchem_cids(pert_raw, PATHS, config=CONFIG)

2026-01-29 19:57:15 | [INFO] Mapping compounds to PubChem CIDs

2026-01-29 19:57:15 | [WARNING] Error standardizing pubchem_cid: invalid literal for int() with base 10: 'MLS003116075'

2026-01-29 19:57:16 | [INFO] Loaded cache from lincs_data/processed/pubchem_cache.json with 21402 entries
2026-01-29 19:57:16 | [INFO] Processing 20416 compounds
2026-01-29 19:57:16 | [INFO] Processed 50/20416 compounds (50 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 100/20416 compounds (100 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 150/20416 compounds (150 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 200/20416 compounds (200 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 250/20416 compounds (250 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 300/20416 compounds (300 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 350/20416 compounds (350 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 400/20416 compounds (400 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 450/20416 compounds (450 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 500/20416 compounds (500 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 550/20416 compounds (550 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 600/20416 compounds (600 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 650/20416 compounds (650 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 700/20416 compounds (700 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 750/20416 compounds (750 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 800/20416 compounds (800 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 850/20416 compounds (850 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 900/20416 compounds (900 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 950/20416 compounds (950 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 1000/20416 compounds (1000 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 1050/20416 compounds (1050 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 1100/20416 compounds (1100 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 1150/20416 compounds (1150 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 1200/20416 compounds (1200 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 1250/20416 compounds (1250 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 1300/20416 compounds (1300 mapped so far)
2026-01-29 19:57:16 | [INFO] Processed 1350/20416 compounds (1350 mapped so far)

[19:57:17] SMILES Parse Error: syntax error while parsing: -666
[19:57:17] SMILES Parse Error: check for mistakes around position 1:
[19:57:17] -666
[19:57:17] ^
[19:57:23] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:25 | [INFO] Processed 1400/20416 compounds (1399 mapped so far)
2026-01-29 19:57:25 | [INFO] Processed 1450/20416 compounds (1449 mapped so far)
2026-01-29 19:57:25 | [INFO] Processed 1500/20416 compounds (1499 mapped so far)
2026-01-29 19:57:25 | [INFO] Processed 1550/20416 compounds (1549 mapped so far)
2026-01-29 19:57:25 | [INFO] Processed 1600/20416 compounds (1599 mapped so far)
2026-01-29 19:57:25 | [INFO] Processed 1650/20416 compounds (1649 mapped so far)
2026-01-29 19:57:25 | [INFO] Processed 1700/20416 compounds (1699 mapped so far)
2026-01-29 19:57:25 | [INFO] Processed 1750/20416 compounds (1749 mapped so far)

[19:57:25] SMILES Parse Error: syntax error while parsing: -666
[19:57:25] SMILES Parse Error: check for mistakes around position 1:
[19:57:25] -666
[19:57:25] ^
[19:57:25] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:26 | [INFO] Processed 1800/20416 compounds (1798 mapped so far)
2026-01-29 19:57:26 | [INFO] Processed 1850/20416 compounds (1848 mapped so far)
2026-01-29 19:57:26 | [INFO] Processed 1900/20416 compounds (1898 mapped so far)
2026-01-29 19:57:26 | [INFO] Processed 1950/20416 compounds (1948 mapped so far)
2026-01-29 19:57:26 | [INFO] Processed 2000/20416 compounds (1998 mapped so far)
2026-01-29 19:57:26 | [INFO] Processed 2050/20416 compounds (2048 mapped so far)
2026-01-29 19:57:26 | [INFO] Processed 2100/20416 compounds (2098 mapped so far)
2026-01-29 19:57:26 | [INFO] Processed 2150/20416 compounds (2148 mapped so far)

[19:57:26] SMILES Parse Error: syntax error while parsing: -666
[19:57:26] SMILES Parse Error: check for mistakes around position 1:
[19:57:26] -666
[19:57:26] ^
[19:57:26] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:27] SMILES Parse Error: syntax error while parsing: -666
[19:57:27] SMILES Parse Error: check for mistakes around position 1:
[19:57:27] -666
[19:57:27] ^
[19:57:27] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:27 | [INFO] Processed 2200/20416 compounds (2196 mapped so far)
2026-01-29 19:57:27 | [INFO] Processed 2250/20416 compounds (2246 mapped so far)
2026-01-29 19:57:27 | [INFO] Processed 2300/20416 compounds (2296 mapped so far)
2026-01-29 19:57:27 | [INFO] Processed 2350/20416 compounds (2346 mapped so far)
2026-01-29 19:57:27 | [INFO] Processed 2400/20416 compounds (2396 mapped so far)
2026-01-29 19:57:27 | [INFO] Processed 2450/20416 compounds (2446 mapped so far)
2026-01-29 19:57:27 | [INFO] Processed 2500/20416 compounds (2496 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2550/20416 compounds (2546 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2600/20416 compounds (2596 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2650/20416 compounds (2646 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2700/20416 compounds (2696 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2750/20416 compounds (2746 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2800/20416 compounds (2796 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2850/20416 compounds (2846 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2900/20416 compounds (2896 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 2950/20416 compounds (2946 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3000/20416 compounds (2996 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3050/20416 compounds (3046 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3100/20416 compounds (3096 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3150/20416 compounds (3146 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3200/20416 compounds (3196 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3250/20416 compounds (3246 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3300/20416 compounds (3296 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3350/20416 compounds (3346 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3400/20416 compounds (3396 mapped so far)

[19:57:28] SMILES Parse Error: syntax error while parsing: -666
[19:57:28] SMILES Parse Error: check for mistakes around position 1:
[19:57:28] -666
[19:57:28] ^
[19:57:28] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:28 | [INFO] Processed 3450/20416 compounds (3445 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3500/20416 compounds (3495 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3550/20416 compounds (3545 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3600/20416 compounds (3595 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3650/20416 compounds (3645 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3700/20416 compounds (3695 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3750/20416 compounds (3745 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3800/20416 compounds (3795 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3850/20416 compounds (3845 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3900/20416 compounds (3895 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 3950/20416 compounds (3945 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4000/20416 compounds (3995 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4050/20416 compounds (4045 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4100/20416 compounds (4095 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4150/20416 compounds (4145 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4200/20416 compounds (4195 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4250/20416 compounds (4245 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4300/20416 compounds (4295 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4350/20416 compounds (4345 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4400/20416 compounds (4395 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4450/20416 compounds (4445 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4500/20416 compounds (4495 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4550/20416 compounds (4545 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4600/20416 compounds (4595 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4650/20416 compounds (4645 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4700/20416 compounds (4695 mapped so far)
2026-01-29 19:57:28 | [INFO] Processed 4750/20416 compounds (4745 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 4800/20416 compounds (4795 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 4850/20416 compounds (4845 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 4900/20416 compounds (4895 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 4950/20416 compounds (4945 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5000/20416 compounds (4995 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5050/20416 compounds (5045 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5100/20416 compounds (5095 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5150/20416 compounds (5145 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5200/20416 compounds (5195 mapped so far)

[19:57:29] SMILES Parse Error: syntax error while parsing: -666
[19:57:29] SMILES Parse Error: check for mistakes around position 1:
[19:57:29] -666
[19:57:29] ^
[19:57:29] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:29 | [INFO] Processed 5250/20416 compounds (5244 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5300/20416 compounds (5294 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5350/20416 compounds (5344 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5400/20416 compounds (5394 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5450/20416 compounds (5444 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5500/20416 compounds (5494 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5550/20416 compounds (5544 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5600/20416 compounds (5594 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5650/20416 compounds (5644 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5700/20416 compounds (5694 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5750/20416 compounds (5744 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5800/20416 compounds (5794 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5850/20416 compounds (5844 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5900/20416 compounds (5894 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 5950/20416 compounds (5944 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 6000/20416 compounds (5994 mapped so far)
2026-01-29 19:57:29 | [INFO] Processed 6050/20416 compounds (6044 mapped so far)

[19:57:29] SMILES Parse Error: syntax error while parsing: -666
[19:57:29] SMILES Parse Error: check for mistakes around position 1:
[19:57:29] -666
[19:57:29] ^
[19:57:29] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:30 | [INFO] Processed 6100/20416 compounds (6093 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6150/20416 compounds (6143 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6200/20416 compounds (6193 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6250/20416 compounds (6243 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6300/20416 compounds (6293 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6350/20416 compounds (6343 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6400/20416 compounds (6393 mapped so far)

[19:57:30] SMILES Parse Error: syntax error while parsing: -666
[19:57:30] SMILES Parse Error: check for mistakes around position 1:
[19:57:30] -666
[19:57:30] ^
[19:57:30] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:30 | [INFO] Processed 6450/20416 compounds (6442 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6500/20416 compounds (6492 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6550/20416 compounds (6542 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6600/20416 compounds (6592 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6650/20416 compounds (6642 mapped so far)
2026-01-29 19:57:30 | [INFO] Processed 6700/20416 compounds (6692 mapped so far)

[19:57:30] SMILES Parse Error: syntax error while parsing: -666
[19:57:30] SMILES Parse Error: check for mistakes around position 1:
[19:57:30] -666
[19:57:30] ^
[19:57:30] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:31 | [INFO] Processed 6750/20416 compounds (6741 mapped so far)
2026-01-29 19:57:31 | [INFO] Processed 6800/20416 compounds (6791 mapped so far)
2026-01-29 19:57:31 | [INFO] Processed 6850/20416 compounds (6841 mapped so far)

[19:57:31] SMILES Parse Error: syntax error while parsing: -666
[19:57:31] SMILES Parse Error: check for mistakes around position 1:
[19:57:31] -666
[19:57:31] ^
[19:57:31] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:32 | [INFO] Processed 6900/20416 compounds (6890 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 6950/20416 compounds (6940 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7000/20416 compounds (6990 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7050/20416 compounds (7040 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7100/20416 compounds (7090 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7150/20416 compounds (7140 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7200/20416 compounds (7190 mapped so far)

[19:57:32] SMILES Parse Error: syntax error while parsing: -666
[19:57:32] SMILES Parse Error: check for mistakes around position 1:
[19:57:32] -666
[19:57:32] ^
[19:57:32] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:32 | [INFO] Processed 7250/20416 compounds (7239 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7300/20416 compounds (7289 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7350/20416 compounds (7339 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7400/20416 compounds (7389 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7450/20416 compounds (7439 mapped so far)
2026-01-29 19:57:32 | [INFO] Processed 7500/20416 compounds (7489 mapped so far)

[19:57:32] SMILES Parse Error: syntax error while parsing: -666
[19:57:32] SMILES Parse Error: check for mistakes around position 1:
[19:57:32] -666
[19:57:32] ^
[19:57:32] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:33 | [INFO] Processed 7550/20416 compounds (7538 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 7600/20416 compounds (7588 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 7650/20416 compounds (7638 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 7700/20416 compounds (7688 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 7750/20416 compounds (7738 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 7800/20416 compounds (7788 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 7850/20416 compounds (7838 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 7900/20416 compounds (7888 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 7950/20416 compounds (7938 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 8000/20416 compounds (7988 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 8050/20416 compounds (8038 mapped so far)
2026-01-29 19:57:33 | [INFO] Processed 8100/20416 compounds (8088 mapped so far)

[19:57:33] SMILES Parse Error: syntax error while parsing: -666
[19:57:33] SMILES Parse Error: check for mistakes around position 1:
[19:57:33] -666
[19:57:33] ^
[19:57:33] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:34 | [INFO] Processed 8150/20416 compounds (8137 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8200/20416 compounds (8187 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8250/20416 compounds (8237 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8300/20416 compounds (8287 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8350/20416 compounds (8337 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8400/20416 compounds (8387 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8450/20416 compounds (8437 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8500/20416 compounds (8487 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8550/20416 compounds (8537 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8600/20416 compounds (8587 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8650/20416 compounds (8637 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8700/20416 compounds (8687 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8750/20416 compounds (8737 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8800/20416 compounds (8787 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8850/20416 compounds (8837 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8900/20416 compounds (8887 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 8950/20416 compounds (8937 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9000/20416 compounds (8987 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9050/20416 compounds (9037 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9100/20416 compounds (9087 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9150/20416 compounds (9137 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9200/20416 compounds (9187 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9250/20416 compounds (9237 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9300/20416 compounds (9287 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9350/20416 compounds (9337 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9400/20416 compounds (9387 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9450/20416 compounds (9437 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9500/20416 compounds (9487 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9550/20416 compounds (9537 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9600/20416 compounds (9587 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9650/20416 compounds (9637 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9700/20416 compounds (9687 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9750/20416 compounds (9737 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9800/20416 compounds (9787 mapped so far)
2026-01-29 19:57:34 | [INFO] Processed 9850/20416 compounds (9837 mapped so far)

[19:57:34] SMILES Parse Error: syntax error while parsing: -666
[19:57:34] SMILES Parse Error: check for mistakes around position 1:
[19:57:34] -666
[19:57:34] ^
[19:57:34] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:35 | [INFO] Processed 9900/20416 compounds (9886 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 9950/20416 compounds (9936 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10000/20416 compounds (9986 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10050/20416 compounds (10036 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10100/20416 compounds (10086 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10150/20416 compounds (10136 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10200/20416 compounds (10186 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10250/20416 compounds (10236 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10300/20416 compounds (10286 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10350/20416 compounds (10336 mapped so far)

[19:57:35] SMILES Parse Error: syntax error while parsing: -666
[19:57:35] SMILES Parse Error: check for mistakes around position 1:
[19:57:35] -666
[19:57:35] ^
[19:57:35] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:35 | [INFO] Processed 10400/20416 compounds (10385 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10450/20416 compounds (10435 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10500/20416 compounds (10485 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10550/20416 compounds (10535 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10600/20416 compounds (10585 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10650/20416 compounds (10635 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10700/20416 compounds (10685 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10750/20416 compounds (10735 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10800/20416 compounds (10785 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10850/20416 compounds (10835 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10900/20416 compounds (10885 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 10950/20416 compounds (10935 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 11000/20416 compounds (10985 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 11050/20416 compounds (11035 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 11100/20416 compounds (11085 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 11150/20416 compounds (11135 mapped so far)
2026-01-29 19:57:35 | [INFO] Processed 11200/20416 compounds (11185 mapped so far)

[19:57:35] SMILES Parse Error: syntax error while parsing: -666
[19:57:35] SMILES Parse Error: check for mistakes around position 1:
[19:57:35] -666
[19:57:35] ^
[19:57:35] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:36 | [INFO] Processed 11250/20416 compounds (11234 mapped so far)
2026-01-29 19:57:36 | [INFO] Processed 11300/20416 compounds (11284 mapped so far)
2026-01-29 19:57:36 | [INFO] Processed 11350/20416 compounds (11334 mapped so far)
2026-01-29 19:57:36 | [INFO] Processed 11400/20416 compounds (11384 mapped so far)
2026-01-29 19:57:36 | [INFO] Processed 11450/20416 compounds (11434 mapped so far)
2026-01-29 19:57:36 | [INFO] Processed 11500/20416 compounds (11484 mapped so far)
2026-01-29 19:57:36 | [INFO] Processed 11550/20416 compounds (11534 mapped so far)
2026-01-29 19:57:36 | [INFO] Processed 11600/20416 compounds (11584 mapped so far)

[19:57:36] SMILES Parse Error: syntax error while parsing: -666
[19:57:36] SMILES Parse Error: check for mistakes around position 1:
[19:57:36] -666
[19:57:36] ^
[19:57:36] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:37 | [INFO] Processed 11650/20416 compounds (11633 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 11700/20416 compounds (11683 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 11750/20416 compounds (11733 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 11800/20416 compounds (11783 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 11850/20416 compounds (11833 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 11900/20416 compounds (11883 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 11950/20416 compounds (11933 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12000/20416 compounds (11983 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12050/20416 compounds (12033 mapped so far)

[19:57:37] SMILES Parse Error: syntax error while parsing: -666
[19:57:37] SMILES Parse Error: check for mistakes around position 1:
[19:57:37] -666
[19:57:37] ^
[19:57:37] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:37 | [INFO] Processed 12100/20416 compounds (12082 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12150/20416 compounds (12132 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12200/20416 compounds (12182 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12250/20416 compounds (12232 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12300/20416 compounds (12282 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12350/20416 compounds (12332 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12400/20416 compounds (12382 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12450/20416 compounds (12432 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12500/20416 compounds (12482 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12550/20416 compounds (12532 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12600/20416 compounds (12582 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12650/20416 compounds (12632 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12700/20416 compounds (12682 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12750/20416 compounds (12732 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12800/20416 compounds (12782 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12850/20416 compounds (12832 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12900/20416 compounds (12882 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 12950/20416 compounds (12932 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 13000/20416 compounds (12982 mapped so far)
2026-01-29 19:57:37 | [INFO] Processed 13050/20416 compounds (13032 mapped so far)

[19:57:37] SMILES Parse Error: syntax error while parsing: -666
[19:57:37] SMILES Parse Error: check for mistakes around position 1:
[19:57:37] -666
[19:57:37] ^
[19:57:37] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:38 | [INFO] Processed 13100/20416 compounds (13081 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13150/20416 compounds (13131 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13200/20416 compounds (13181 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13250/20416 compounds (13231 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13300/20416 compounds (13281 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13350/20416 compounds (13331 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13400/20416 compounds (13381 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13450/20416 compounds (13431 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13500/20416 compounds (13481 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13550/20416 compounds (13531 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13600/20416 compounds (13581 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13650/20416 compounds (13631 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13700/20416 compounds (13681 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13750/20416 compounds (13731 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13800/20416 compounds (13781 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13850/20416 compounds (13831 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13900/20416 compounds (13881 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 13950/20416 compounds (13931 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14000/20416 compounds (13981 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14050/20416 compounds (14031 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14100/20416 compounds (14081 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14150/20416 compounds (14131 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14200/20416 compounds (14181 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14250/20416 compounds (14231 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14300/20416 compounds (14281 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14350/20416 compounds (14331 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14400/20416 compounds (14381 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14450/20416 compounds (14431 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14500/20416 compounds (14481 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14550/20416 compounds (14531 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14600/20416 compounds (14581 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14650/20416 compounds (14631 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14700/20416 compounds (14681 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14750/20416 compounds (14731 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14800/20416 compounds (14781 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14850/20416 compounds (14831 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14900/20416 compounds (14881 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 14950/20416 compounds (14931 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15000/20416 compounds (14981 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15050/20416 compounds (15031 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15100/20416 compounds (15081 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15150/20416 compounds (15131 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15200/20416 compounds (15181 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15250/20416 compounds (15231 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15300/20416 compounds (15281 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15350/20416 compounds (15331 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15400/20416 compounds (15381 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15450/20416 compounds (15431 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15500/20416 compounds (15481 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15550/20416 compounds (15531 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15600/20416 compounds (15581 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15650/20416 compounds (15631 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15700/20416 compounds (15681 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15750/20416 compounds (15731 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15800/20416 compounds (15781 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15850/20416 compounds (15831 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15900/20416 compounds (15881 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 15950/20416 compounds (15931 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16000/20416 compounds (15981 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16050/20416 compounds (16031 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16100/20416 compounds (16081 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16150/20416 compounds (16131 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16200/20416 compounds (16181 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16250/20416 compounds (16231 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16300/20416 compounds (16281 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16350/20416 compounds (16331 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16400/20416 compounds (16381 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16450/20416 compounds (16431 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16500/20416 compounds (16481 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16550/20416 compounds (16531 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16600/20416 compounds (16581 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16650/20416 compounds (16631 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16700/20416 compounds (16681 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16750/20416 compounds (16731 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16800/20416 compounds (16781 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16850/20416 compounds (16831 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16900/20416 compounds (16881 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 16950/20416 compounds (16931 mapped so far)
2026-01-29 19:57:38 | [INFO] Processed 17000/20416 compounds (16981 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17050/20416 compounds (17031 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17100/20416 compounds (17081 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17150/20416 compounds (17131 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17200/20416 compounds (17181 mapped so far)

[19:57:39] SMILES Parse Error: syntax error while parsing: -666
[19:57:39] SMILES Parse Error: check for mistakes around position 1:
[19:57:39] -666
[19:57:39] ^
[19:57:39] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:39 | [INFO] Processed 17250/20416 compounds (17230 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17300/20416 compounds (17280 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17350/20416 compounds (17330 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17400/20416 compounds (17380 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17450/20416 compounds (17430 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17500/20416 compounds (17480 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17550/20416 compounds (17530 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17600/20416 compounds (17580 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17650/20416 compounds (17630 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17700/20416 compounds (17680 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17750/20416 compounds (17730 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17800/20416 compounds (17780 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17850/20416 compounds (17830 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17900/20416 compounds (17880 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 17950/20416 compounds (17930 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18000/20416 compounds (17980 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18050/20416 compounds (18030 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18100/20416 compounds (18080 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18150/20416 compounds (18130 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18200/20416 compounds (18180 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18250/20416 compounds (18230 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18300/20416 compounds (18280 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18350/20416 compounds (18330 mapped so far)
2026-01-29 19:57:39 | [INFO] Processed 18400/20416 compounds (18380 mapped so far)

[19:57:39] SMILES Parse Error: syntax error while parsing: -666
[19:57:39] SMILES Parse Error: check for mistakes around position 1:
[19:57:39] -666
[19:57:39] ^
[19:57:39] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:40 | [INFO] Processed 18450/20416 compounds (18429 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18500/20416 compounds (18479 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18550/20416 compounds (18529 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18600/20416 compounds (18579 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18650/20416 compounds (18629 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18700/20416 compounds (18679 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18750/20416 compounds (18729 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18800/20416 compounds (18779 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18850/20416 compounds (18829 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18900/20416 compounds (18879 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 18950/20416 compounds (18929 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19000/20416 compounds (18979 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19050/20416 compounds (19029 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19100/20416 compounds (19079 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19150/20416 compounds (19129 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19200/20416 compounds (19179 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19250/20416 compounds (19229 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19300/20416 compounds (19279 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19350/20416 compounds (19329 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19400/20416 compounds (19379 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19450/20416 compounds (19429 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19500/20416 compounds (19479 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19550/20416 compounds (19529 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19600/20416 compounds (19579 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19650/20416 compounds (19629 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19700/20416 compounds (19679 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19750/20416 compounds (19729 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19800/20416 compounds (19779 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19850/20416 compounds (19829 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19900/20416 compounds (19879 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 19950/20416 compounds (19929 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 20000/20416 compounds (19979 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 20050/20416 compounds (20029 mapped so far)
2026-01-29 19:57:40 | [INFO] Processed 20100/20416 compounds (20079 mapped so far)

[19:57:40] SMILES Parse Error: syntax error while parsing: -666
[19:57:40] SMILES Parse Error: check for mistakes around position 1:
[19:57:40] -666
[19:57:40] ^
[19:57:40] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:41 | [INFO] Processed 20150/20416 compounds (20128 mapped so far)
2026-01-29 19:57:41 | [INFO] Processed 20200/20416 compounds (20178 mapped so far)
2026-01-29 19:57:41 | [INFO] Processed 20250/20416 compounds (20228 mapped so far)
2026-01-29 19:57:41 | [INFO] Processed 20300/20416 compounds (20278 mapped so far)
2026-01-29 19:57:41 | [INFO] Processed 20350/20416 compounds (20328 mapped so far)

[19:57:41] SMILES Parse Error: syntax error while parsing: -666
[19:57:41] SMILES Parse Error: check for mistakes around position 1:
[19:57:41] -666
[19:57:41] ^
[19:57:41] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:42] SMILES Parse Error: syntax error while parsing: -666
[19:57:42] SMILES Parse Error: check for mistakes around position 1:
[19:57:42] -666
[19:57:42] ^
[19:57:42] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:42] SMILES Parse Error: syntax error while parsing: -666
[19:57:42] SMILES Parse Error: check for mistakes around position 1:
[19:57:42] -666
[19:57:42] ^
[19:57:42] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:43] SMILES Parse Error: syntax error while parsing: restricted
[19:57:43] SMILES Parse Error: check for mistakes around position 1:
[19:57:43] restricted
[19:57:43] ^
[19:57:43] SMILES Parse Error: Failed parsing SMILES 'restricted' for input: 'restricted'
[19:57:43] SMILES Parse Error: syntax error while parsing: restricted
[19:57:43] SMILES Parse Error: check for mistakes around position 1:
[19:57:43] restricted
[19:57:43] ^
[19:57:43] SMILES Parse Error: Failed parsing SMILES 'restricted' for input: 'restricted'
[19:57:44] SMILES Parse Error: syntax error while parsing: -666
[19:57:44] SMILES Parse Error: check for mistakes around position 1:
[19:57:44] -666
[19:57:44] ^
[19:57:44] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:44] SMILES Parse Error: syntax error while parsing: -666
[19:57:44] SMILES Parse Error: check for mistakes around position 1:
[19:57:44] -666
[19:57:44] ^
[19:57:44] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:45] SMILES Parse Error: syntax error while parsing: -666
[19:57:45] SMILES Parse Error: check for mistakes around position 1:
[19:57:45] -666
[19:57:45] ^
[19:57:45] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:46] SMILES Parse Error: syntax error while parsing: restricted
[19:57:46] SMILES Parse Error: check for mistakes around position 1:
[19:57:46] restricted
[19:57:46] ^
[19:57:46] SMILES Parse Error: Failed parsing SMILES 'restricted' for input: 'restricted'
[19:57:46] SMILES Parse Error: syntax error while parsing: -666
[19:57:46] SMILES Parse Error: check for mistakes around position 1:
[19:57:46] -666
[19:57:46] ^
[19:57:46] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:47] SMILES Parse Error: syntax error while parsing: restricted
[19:57:47] SMILES Parse Error: check for mistakes around position 1:
[19:57:47] restricted
[19:57:47] ^
[19:57:47] SMILES Parse Error: Failed parsing SMILES 'restricted' for input: 'restricted'
[19:57:47] SMILES Parse Error: syntax error while parsing: -666
[19:57:47] SMILES Parse Error: check for mistakes around position 1:
[19:57:47] -666
[19:57:47] ^
[19:57:47] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:48] SMILES Parse Error: syntax error while parsing: -666
[19:57:48] SMILES Parse Error: check for mistakes around position 1:
[19:57:48] -666
[19:57:48] ^
[19:57:48] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:48] SMILES Parse Error: syntax error while parsing: -666
[19:57:48] SMILES Parse Error: check for mistakes around position 1:
[19:57:48] -666
[19:57:48] ^
[19:57:48] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:49] SMILES Parse Error: syntax error while parsing: -666
[19:57:49] SMILES Parse Error: check for mistakes around position 1:
[19:57:49] -666
[19:57:49] ^
[19:57:49] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:50] SMILES Parse Error: syntax error while parsing: -666
[19:57:50] SMILES Parse Error: check for mistakes around position 1:
[19:57:50] -666
[19:57:50] ^
[19:57:50] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:50] SMILES Parse Error: syntax error while parsing: -666
[19:57:50] SMILES Parse Error: check for mistakes around position 1:
[19:57:50] -666
[19:57:50] ^
[19:57:50] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:51] SMILES Parse Error: syntax error while parsing: -666
[19:57:51] SMILES Parse Error: check for mistakes around position 1:
[19:57:51] -666
[19:57:51] ^
[19:57:51] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:51] SMILES Parse Error: syntax error while parsing: restricted
[19:57:51] SMILES Parse Error: check for mistakes around position 1:
[19:57:51] restricted
[19:57:51] ^
[19:57:51] SMILES Parse Error: Failed parsing SMILES 'restricted' for input: 'restricted'
[19:57:52] SMILES Parse Error: syntax error while parsing: -666
[19:57:52] SMILES Parse Error: check for mistakes around position 1:
[19:57:52] -666
[19:57:52] ^
[19:57:52] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:52] SMILES Parse Error: syntax error while parsing: -666
[19:57:52] SMILES Parse Error: check for mistakes around position 1:
[19:57:52] -666
[19:57:52] ^
[19:57:52] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:53] SMILES Parse Error: syntax error while parsing: -666
[19:57:53] SMILES Parse Error: check for mistakes around position 1:
[19:57:53] -666
[19:57:53] ^
[19:57:53] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:54 | [INFO] Processed 20400/20416 compounds (20356 mapped so far)

[19:57:54] SMILES Parse Error: syntax error while parsing: -666
[19:57:54] SMILES Parse Error: check for mistakes around position 1:
[19:57:54] -666
[19:57:54] ^
[19:57:54] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:54] SMILES Parse Error: syntax error while parsing: -666
[19:57:54] SMILES Parse Error: check for mistakes around position 1:
[19:57:54] -666
[19:57:54] ^
[19:57:54] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:55] SMILES Parse Error: syntax error while parsing: -666
[19:57:55] SMILES Parse Error: check for mistakes around position 1:
[19:57:55] -666
[19:57:55] ^
[19:57:55] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:55] SMILES Parse Error: syntax error while parsing: -666
[19:57:55] SMILES Parse Error: check for mistakes around position 1:
[19:57:55] -666
[19:57:55] ^
[19:57:55] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:56] SMILES Parse Error: syntax error while parsing: -666
[19:57:56] SMILES Parse Error: check for mistakes around position 1:
[19:57:56] -666
[19:57:56] ^
[19:57:56] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:57] SMILES Parse Error: syntax error while parsing: -666
[19:57:57] SMILES Parse Error: check for mistakes around position 1:
[19:57:57] -666
[19:57:57] ^
[19:57:57] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:57] SMILES Parse Error: syntax error while parsing: -666
[19:57:57] SMILES Parse Error: check for mistakes around position 1:
[19:57:57] -666
[19:57:57] ^
[19:57:57] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'
[19:57:58] SMILES Parse Error: syntax error while parsing: -666
[19:57:58] SMILES Parse Error: check for mistakes around position 1:
[19:57:58] -666
[19:57:58] ^
[19:57:58] SMILES Parse Error: Failed parsing SMILES '-666' for input: '-666'

2026-01-29 19:57:58 | [INFO] Mapped 20364 out of 20416 compounds to PubChem CIDs

In [41]:
# Process signature metadata
sig = process_sig_metadata(sig_raw, cellinfo, pert_raw, CONFIG, PATHS)

2026-01-29 19:59:01 | [INFO]   Processing signature metadata

In [42]:
logger.info('  Building .obs dataframe')
obs = build_obs_dataframe(sig, dataset=CONFIG.get("dataset"))

2026-01-29 19:59:46 | [INFO]   Building .obs dataframe

In [43]:
obs

,lincs_sig_id,distil_id,plate,well,cell_type,perturbagen,pert_type,is_control,pert_dose_uM,pert_dose,...,development_stage,organism,sex,self_reported_ethnicity,pubchem_cid,psbulk_cells,psbulk_counts,source_gctx,sample_id,pert_type_init
sig_id,,,,,,,,,,,,,,,,,,,,,
AML001_CD34_24H:A05,0,AML001_CD34_24H_X1_F1B10:A05,None,None,CD34,DMSO,compound,True,0.00000,0.1 %,...,unknown,human,NaN,None,679,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_DMSO_CD34,ctl_vehicle
AML001_CD34_24H:A06,1,AML001_CD34_24H_X3_F1B10:A06,None,None,CD34,DMSO,compound,True,0.00000,0.1 %,...,unknown,human,NaN,None,679,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_DMSO_CD34,ctl_vehicle
AML001_CD34_24H:B05,2,AML001_CD34_24H_X1_F1B10:B05|AML001_CD34_24H_X...,None,None,CD34,DMSO,compound,True,0.00000,0.1 %,...,unknown,human,NaN,None,679,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_DMSO_CD34,ctl_vehicle
AML001_CD34_24H:B06,3,AML001_CD34_24H_X3_F1B10:B06,None,None,CD34,DMSO,compound,True,0.00000,0.1 %,...,unknown,human,NaN,None,679,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_DMSO_CD34,ctl_vehicle
AML001_CD34_24H:BRD-A03772856:0.37037,4,AML001_CD34_24H_X1_F1B10:J04|AML001_CD34_24H_X...,None,None,CD34,BRD-A03772856,compound,False,0.37037,0.37037 µM,...,unknown,human,NaN,None,3237298,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_BRD-A03772856_CD34,trt_cp
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
TAK004_U2OS_96H:TRCN0000370007:1,473642,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:J10|TAK004_U...,None,None,CVCL_0042,WWTR1,genetic,False,NaN,1.0 µL,...,15-year-old stage,human,female,Caucasian,None,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_WWTR1_CVCL_0042,trt_sh
TAK004_U2OS_96H:TRCN0000370678:1,473643,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:E02|TAK004_U...,None,None,CVCL_0042,GRB10,genetic,False,NaN,1.0 µL,...,15-year-old stage,human,female,Caucasian,None,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_GRB10_CVCL_0042,trt_sh
TAK004_U2OS_96H:TRCN0000370697:1,473644,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:A18|TAK004_U...,None,None,CVCL_0042,GRB10,genetic,False,NaN,1.0 µL,...,15-year-old stage,human,female,Caucasian,None,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_GRB10_CVCL_0042,trt_sh
TAK004_U2OS_96H:TRCN0000370751:1,473645,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:I12|TAK004_U...,None,None,CVCL_0042,GRB10,genetic,False,NaN,1.0 µL,...,15-year-old stage,human,female,Caucasian,None,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_GRB10_CVCL_0042,trt_sh
TAK004_U2OS_96H:TRCN0000381509:1,473646,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:L01|TAK004_U...,None,None,CVCL_0042,CDC42,genetic,False,NaN,1.0 µL,...,15-year-old stage,human,female,Caucasian,None,None,None,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,None_None_CDC42_CVCL_0042,trt_sh

In [44]:
obs['sig_id'] = obs.index

In [45]:
logger.info('  Enforcing strict obs schema')
obs_for_schema = enforce_obs_schema(obs)

2026-01-29 20:00:50 | [INFO]   Enforcing strict obs schema

In [47]:
logger.info('  Processing gene annotations')
var = process_gene_annotations(geneinfo, FULL_GENE_MATRIX)

2026-01-29 20:01:26 | [INFO]   Processing gene annotations
2026-01-29 20:01:26 | [INFO]   Restricting to 978 landmark genes
2026-01-29 20:01:31 | [INFO] Processed 50/978 entrez ids (50 mapped so far)
2026-01-29 20:01:36 | [INFO] Processed 100/978 entrez ids (100 mapped so far)
2026-01-29 20:01:42 | [INFO] Processed 150/978 entrez ids (150 mapped so far)
2026-01-29 20:01:47 | [INFO] Processed 200/978 entrez ids (200 mapped so far)
2026-01-29 20:01:52 | [INFO] Processed 250/978 entrez ids (250 mapped so far)
2026-01-29 20:01:57 | [INFO] Processed 300/978 entrez ids (300 mapped so far)
2026-01-29 20:02:02 | [INFO] Processed 350/978 entrez ids (350 mapped so far)
2026-01-29 20:02:07 | [INFO] Processed 400/978 entrez ids (400 mapped so far)
2026-01-29 20:02:12 | [INFO] Processed 450/978 entrez ids (450 mapped so far)
2026-01-29 20:02:17 | [INFO] Processed 500/978 entrez ids (500 mapped so far)
2026-01-29 20:02:22 | [INFO] Processed 550/978 entrez ids (550 mapped so far)
2026-01-29 20:02:27 | [INFO] Processed 600/978 entrez ids (600 mapped so far)
2026-01-29 20:02:32 | [INFO] Processed 650/978 entrez ids (650 mapped so far)
2026-01-29 20:02:37 | [INFO] Processed 700/978 entrez ids (700 mapped so far)
2026-01-29 20:02:42 | [INFO] Processed 750/978 entrez ids (750 mapped so far)
2026-01-29 20:02:47 | [INFO] Processed 800/978 entrez ids (800 mapped so far)
2026-01-29 20:02:52 | [INFO] Processed 850/978 entrez ids (850 mapped so far)
2026-01-29 20:02:57 | [INFO] Processed 900/978 entrez ids (900 mapped so far)
2026-01-29 20:03:02 | [INFO] Processed 950/978 entrez ids (950 mapped so far)
2026-01-29 20:03:05 | [INFO] Processed 978/978 entrez ids (978 mapped so far)

In [48]:
logger.info('  Matching obs to GCTX column IDs')
obs_helpers = build_obs_helpers(obs, PATHS["level5_gctx"])

2026-01-29 20:03:14 | [INFO]   Matching obs to GCTX column IDs
2026-01-29 20:03:16 | [INFO]   Loaded 473,647 column IDs from GSE92742_Broad_LINCS_Level5_COMPZ.MODZ_n473647x12328.gctx
2026-01-29 20:03:17 | [INFO]   Using obs index to subset GCTX (473647/473647 samples match)

In [49]:
obs_helpers

,source_gctx,gctx_id
sig_id,,
AML001_CD34_24H:A05,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,AML001_CD34_24H:A05
AML001_CD34_24H:A06,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,AML001_CD34_24H:A06
AML001_CD34_24H:B05,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,AML001_CD34_24H:B05
AML001_CD34_24H:B06,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,AML001_CD34_24H:B06
AML001_CD34_24H:BRD-A03772856:0.37037,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,AML001_CD34_24H:BRD-A03772856:0.37037
...,...,...
TAK004_U2OS_96H:TRCN0000370007:1,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,TAK004_U2OS_96H:TRCN0000370007:1
TAK004_U2OS_96H:TRCN0000370678:1,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,TAK004_U2OS_96H:TRCN0000370678:1
TAK004_U2OS_96H:TRCN0000370697:1,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,TAK004_U2OS_96H:TRCN0000370697:1
TAK004_U2OS_96H:TRCN0000370751:1,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,TAK004_U2OS_96H:TRCN0000370751:1
TAK004_U2OS_96H:TRCN0000381509:1,lincs_data/GSE92742_Broad_LINCS_Level5_COMPZ.M...,TAK004_U2OS_96H:TRCN0000381509:1

In [50]:
sig_raw[sig_raw['pert_type'].isin(['trt_cp']) | (sig_raw['pert_type'].isin(['ctl_vehicle']) & sig_raw['pert_iname'].isin(['DMSO']))]

,sig_id,pert_id,pert_iname,pert_type,cell_id,pert_dose,pert_dose_unit,pert_idose,pert_time,pert_time_unit,pert_itime,distil_id
0,AML001_CD34_24H:A05,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X1_F1B10:A05
1,AML001_CD34_24H:A06,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X3_F1B10:A06
2,AML001_CD34_24H:B05,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X1_F1B10:B05|AML001_CD34_24H_X...
3,AML001_CD34_24H:B06,DMSO,DMSO,ctl_vehicle,CD34,0.1,%,0.1 %,24,h,24 h,AML001_CD34_24H_X3_F1B10:B06
4,AML001_CD34_24H:BRD-A03772856:0.37037,BRD-A03772856,BRD-A03772856,trt_cp,CD34,0.37037,µM,500 nM,24,h,24 h,AML001_CD34_24H_X1_F1B10:J04|AML001_CD34_24H_X...
...,...,...,...,...,...,...,...,...,...,...,...,...
469552,RAD001_PC3_6H:P02,DMSO,DMSO,ctl_vehicle,PC3,-666.0,-666,-666,6,h,6 h,RAD001_PC3_6H_X2_F1B5_DUO52HI53LO:P02
469553,RAD001_PC3_6H:P13,DMSO,DMSO,ctl_vehicle,PC3,-666.0,-666,-666,6,h,6 h,RAD001_PC3_6H_X2_F1B5_DUO52HI53LO:P13
469554,RAD001_PC3_6H:P23,DMSO,DMSO,ctl_vehicle,PC3,-666.0,-666,-666,6,h,6 h,RAD001_PC3_6H_X2_F1B5_DUO52HI53LO:P23
469555,RAD001_PC3_6H:P24,DMSO,DMSO,ctl_vehicle,PC3,-666.0,-666,-666,6,h,6 h,RAD001_PC3_6H_X2_F1B5_DUO52HI53LO:P24
469839,T2D001_MCH58_144H:CMAP-T2DTUNICAMYCIN:-666,CMAP-T2DTUNICAMYCIN,tunicamycin,trt_cp,MCH58,-666.0,-666,-666,144,h,144 h,T2D001_MCH58_144H_X1_B2_UNI5253L:O01|T2D001_MC...

In [51]:
logger.info('  Extracting expression from GCTX')
expr = load_expression(obs_helpers, PATHS["level5_gctx"], gene_ids=var.index.astype(str))

2026-01-29 20:03:54 | [INFO]   Extracting expression from GCTX

/ictstr01/home/icb/olga.novitskaia/deg_venv/lib/python3.10/site-packages/cmapPy/pandasGEXpress/parse_gctx.py:275: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  meta_df = meta_df.apply(lambda x: pd.to_numeric(x, errors="ignore"))
/ictstr01/home/icb/olga.novitskaia/deg_venv/lib/python3.10/site-packages/cmapPy/pandasGEXpress/parse_gctx.py:275: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  meta_df = meta_df.apply(lambda x: pd.to_numeric(x, errors="ignore"))

In [52]:
logger.info('  Assembling AnnData')
padata_processed = assemble_anndata(obs_for_schema, var, expr)

2026-01-29 20:04:38 | [INFO]   Assembling AnnData

/ictstr01/home/icb/olga.novitskaia/deg_venv/lib/python3.10/site-packages/anndata/_core/anndata.py:1756: UserWarning: Observation names are not unique. To make them unique, call `.obs_names_make_unique`.
  utils.warn_names_duplicates("obs")

In [53]:
logger.info(f'  Assembled AnnData: {padata_processed.n_obs:,} × {padata_processed.n_vars:,}')
logger.info('L1000-specific processing completed')

2026-01-29 20:05:36 | [INFO]   Assembled AnnData: 473,647 × 978
2026-01-29 20:05:36 | [INFO] L1000-specific processing completed

In [54]:
padata_processed.obs

,plate,well,cell_type,perturbagen,pert_type,is_control,pert_dose_uM,pert_time_h,suspension_type,tissue,...,guide,dataset,assay,development_stage,organism,sex,self_reported_ethnicity,pubchem_cid,psbulk_cells,psbulk_counts
sample_id,,,,,,,,,,,,,,,,,,,,,
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.00000,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.00000,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.00000,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.00000,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
None_None_BRD-A03772856_CD34,NaN,NaN,CD34,BRD-A03772856,compound,False,0.37037,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,3237298,-666,-666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
None_None_WWTR1_CVCL_0042,NaN,NaN,CVCL_0042,WWTR1,genetic,False,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666
None_None_GRB10_CVCL_0042,NaN,NaN,CVCL_0042,GRB10,genetic,False,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666
None_None_GRB10_CVCL_0042,NaN,NaN,CVCL_0042,GRB10,genetic,False,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666
None_None_GRB10_CVCL_0042,NaN,NaN,CVCL_0042,GRB10,genetic,False,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666
None_None_CDC42_CVCL_0042,NaN,NaN,CVCL_0042,CDC42,genetic,False,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666

In [58]:
# Save the assembled dataset
logger.info(f"Saving assembled dataset to: {'./data/l1000_phase1/level5/' + config['output_file']}")
padata_processed.write_h5ad('./data/l1000_phase1/level5/' + config['output_file'], compression='gzip')
logger.info(f"{'./data/l1000_phase1/level5/' + config['output_file']} assembly complete")

2026-01-29 20:11:51 | [INFO] Saving assembled dataset to: ./data/l1000_phase1/level5/level5_phase1_not_filtered.h5ad
2026-01-29 20:13:39 | [INFO] ./data/l1000_phase1/level5/level5_phase1_not_filtered.h5ad assembly complete

In [59]:
padata_processed[padata_processed.obs['cell_type'] == 'CVCL_0566']

View of AnnData object with n_obs × n_vars = 273 × 978
    obs: 'plate', 'well', 'cell_type', 'perturbagen', 'pert_type', 'is_control', 'pert_dose_uM', 'pert_time_h', 'suspension_type', 'tissue', 'tissue_type', 'disease', 'library', 'stimulation', 'guide', 'dataset', 'assay', 'development_stage', 'organism', 'sex', 'self_reported_ethnicity', 'pubchem_cid', 'psbulk_cells', 'psbulk_counts'
    var: 'symbol'

In [60]:
padata_processed.obs[padata_processed.obs['is_control'] == True]

,plate,well,cell_type,perturbagen,pert_type,is_control,pert_dose_uM,pert_time_h,suspension_type,tissue,...,guide,dataset,assay,development_stage,organism,sex,self_reported_ethnicity,pubchem_cid,psbulk_cells,psbulk_counts
sample_id,,,,,,,,,,,,,,,,,,,,,
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.0,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.0,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.0,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.0,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
None_None_DMSO_CD34,NaN,NaN,CD34,DMSO,compound,True,0.0,24.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,unknown,human,unknown,unknown,679,-666,-666
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
None_None_lacZ_CVCL_0042,NaN,NaN,CVCL_0042,lacZ,genetic,True,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666
None_None_LUCIFERASE_CVCL_0042,NaN,NaN,CVCL_0042,LUCIFERASE,genetic,True,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666
None_None_LUCIFERASE_CVCL_0042,NaN,NaN,CVCL_0042,LUCIFERASE,genetic,True,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666
None_None_LUCIFERASE_CVCL_0042,NaN,NaN,CVCL_0042,LUCIFERASE,genetic,True,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666
None_None_EMPTY_VECTOR_CVCL_0042,NaN,NaN,CVCL_0042,EMPTY_VECTOR,genetic,True,NaN,96.0,cell,bone,...,NaN,LINCS_phase1_level3_epsilon,L1000 mRNA profiling assay,15-year-old stage,human,female,Caucasian,NaN,-666,-666

In [61]:
sig_raw[sig_raw['pert_iname'] == 'LUCIFERASE']

,sig_id,pert_id,pert_iname,pert_type,cell_id,pert_dose,pert_dose_unit,pert_idose,pert_time,pert_time_unit,pert_itime,distil_id
38964,CNS001_A375_96H:LUCIFERASE:-666,CNS001-LUCIFERASE,LUCIFERASE,ctl_vector.cns,A375,-666.0,-666,-666,96,h,96 h,DER001_A375_96H:TRCN0000072248:-666|KDA001_A37...
38975,CNS001_A549_96H:LUCIFERASE:-666,CNS001-LUCIFERASE,LUCIFERASE,ctl_vector.cns,A549,-666.0,-666,-666,96,h,96 h,KDB004_A549_96H:TRCN0000072254:-666|KDA001_A54...
38983,CNS001_ASC_96H:LUCIFERASE:-666,CNS001-LUCIFERASE,LUCIFERASE,ctl_vector.cns,ASC,-666.0,-666,-666,96,h,96 h,KDB001_ASC_96H:TRCN0000072250:-666|KDB008_ASC_...
39004,CNS001_HA1E_96H:LUCIFERASE:-666,CNS001-LUCIFERASE,LUCIFERASE,ctl_vector.cns,HA1E,-666.0,-666,-666,96,h,96 h,KDA010_HA1E_96H:TRCN0000072266:-666|KDA001_HA1...
39015,CNS001_HCC515_96H:LUCIFERASE:-666,CNS001-LUCIFERASE,LUCIFERASE,ctl_vector.cns,HCC515,-666.0,-666,-666,96,h,96 h,DER001_HCC515_96H:TRCN0000072248:-666|KDA005_H...
...,...,...,...,...,...,...,...,...,...,...,...,...
473006,TAK003_HEKTE_96H:TRCN0000072266:-666,TRCN0000072266,LUCIFERASE,ctl_vector,HEKTE,-666.0,-666,-666,96,h,96 h,TAK003_HEKTE_96H_X1_B7_DUO52HI53LO:H21|TAK003_...
473192,TAK003_PC3_96H:TRCN0000072266:-666,TRCN0000072266,LUCIFERASE,ctl_vector,PC3,-666.0,-666,-666,96,h,96 h,TAK003_PC3_96H_X1_B7_DUO52HI53LO:H21|TAK003_PC...
473450,TAK004_U2OS_96H:TRCN0000072246:1,TRCN0000072246,LUCIFERASE,ctl_vector,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:M19|TAK004_U...
473451,TAK004_U2OS_96H:TRCN0000072248:1,TRCN0000072248,LUCIFERASE,ctl_vector,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:M14|TAK004_U...
473452,TAK004_U2OS_96H:TRCN0000072249:1,TRCN0000072249,LUCIFERASE,ctl_vector,U2OS,1.0,µL,1 µL,96,h,96 h,TAK004_U2OS_96H_X1_B6_DUO52HI53LO:J02|TAK004_U...