In [ ]:

'''
https://github.com/ArcInstitute/arc-virtual-cell-atlas/blob/main/scBaseCount/README.md
https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSE139944
https://www.ncbi.nlm.nih.gov/sra?term=SRP228591

https://figshare.com/articles/dataset/sciPlex_dataset/24681285?file=43381398
http://projects.sanderlab.org/scperturb/datavzrd/scPerturb_vzrd_v1/dataset_info/index_1.html
'''

In [1]:
import gcsfs

In [2]:
import pandas as pd

In [3]:
import scanpy as sc

In [4]:
from tqdm import tqdm

In [5]:
fs = gcsfs.GCSFileSystem()

In [6]:
gcp_path = "gs://arc-scbasecount"

In [7]:
fs.ls('gs://arc-scbasecount/')

['arc-scbasecount/2025-02-25',
 'arc-scbasecount/README.md',
 'arc-scbasecount/tmp']

In [108]:
folders_lvl1 = fs.ls('gs://arc-scbasecount/2025-02-25/h5ad')

In [126]:
folder2

'arc-scbasecount/2025-02-25/h5ad/Velocyto/Zea_mays'

In [124]:
for folder1 in tqdm(folders_lvl1):
    folders_lvl2 = fs.ls(folder1)
    for folder2 in tqdm(folders_lvl2):
        if fs.exists(folder2 + '/SRX7101189.h5ad'):
            print(folder2)
        if fs.exists(folder2 + '/SRX7101188.h5ad'):
            print(folder2)
        if fs.exists(folder2 + '/SRX7101187.h5ad'):
            print(folder2)
        if fs.exists(folder2 + '/SRX7101186.h5ad'):
            print(folder2)

  0%|          | 0/5 [00:00<?, ?it/s]
  0%|          | 0/21 [00:00<?, ?it/s]
 10%|▉         | 2/21 [00:03<00:36,  1.91s/it]
 14%|█▍        | 3/21 [00:07<00:48,  2.70s/it]
 19%|█▉        | 4/21 [00:09<00:42,  2.48s/it]
 24%|██▍       | 5/21 [00:11<00:34,  2.17s/it]
 29%|██▊       | 6/21 [00:13<00:33,  2.22s/it]
 33%|███▎      | 7/21 [00:15<00:28,  2.03s/it]
 38%|███▊      | 8/21 [00:17<00:27,  2.14s/it]
 43%|████▎     | 9/21 [00:19<00:24,  2.04s/it]
 48%|████▊     | 10/21 [00:21<00:20,  1.90s/it]
 52%|█████▏    | 11/21 [00:22<00:18,  1.81s/it]
 57%|█████▋    | 12/21 [00:25<00:19,  2.11s/it]
 62%|██████▏   | 13/21 [00:27<00:15,  1.99s/it]
 67%|██████▋   | 14/21 [00:28<00:13,  1.86s/it]
 71%|███████▏  | 15/21 [00:30<00:10,  1.78s/it]
 76%|███████▌  | 16/21 [00:31<00:08,  1.72s/it]
 81%|████████  | 17/21 [00:33<00:06,  1.68s/it]
 86%|████████▌ | 18/21 [00:35<00:04,  1.66s/it]
 90%|█████████ | 19/21 [00:36<00:03,  1.64s/it]
 95%|█████████▌| 20/21 [00:38<00:01,  1.63s/it]
100%|██████████| 21/21 [00:39<00:00,  1.90s/it]
 20%|██        | 1/5 [00:39<02:39, 39.98s/it]
  0%|          | 0/21 [00:00<?, ?it/s]
  5%|▍         | 1/21 [00:01<00:31,  1.58s/it]
 10%|▉         | 2/21 [00:03<00:30,  1.60s/it]
 14%|█▍        | 3/21 [00:04<00:28,  1.60s/it]
 19%|█▉        | 4/21 [00:06<00:27,  1.59s/it]
 24%|██▍       | 5/21 [00:07<00:25,  1.59s/it]
 29%|██▊       | 6/21 [00:09<00:23,  1.59s/it]
 33%|███▎      | 7/21 [00:11<00:22,  1.59s/it]
 38%|███▊      | 8/21 [00:12<00:20,  1.60s/it]
 43%|████▎     | 9/21 [00:14<00:19,  1.60s/it]
 48%|████▊     | 10/21 [00:15<00:17,  1.59s/it]
 57%|█████▋    | 12/21 [00:17<00:11,  1.28s/it]
 62%|██████▏   | 13/21 [00:19<00:10,  1.36s/it]
 67%|██████▋   | 14/21 [00:20<00:09,  1.42s/it]
 71%|███████▏  | 15/21 [00:22<00:08,  1.47s/it]
 76%|███████▌  | 16/21 [00:24<00:07,  1.50s/it]
 81%|████████  | 17/21 [00:25<00:06,  1.53s/it]
 86%|████████▌ | 18/21 [00:27<00:04,  1.56s/it]
 90%|█████████ | 19/21 [00:28<00:03,  1.57s/it]
 95%|█████████▌| 20/21 [00:30<00:01,  1.58s/it]
100%|██████████| 21/21 [00:32<00:00,  1.53s/it]
 40%|████      | 2/5 [01:12<01:46, 35.39s/it]
  0%|          | 0/21 [00:00<?, ?it/s]
  5%|▍         | 1/21 [00:01<00:31,  1.57s/it]
 10%|▉         | 2/21 [00:03<00:30,  1.59s/it]
 14%|█▍        | 3/21 [00:04<00:28,  1.61s/it]
 19%|█▉        | 4/21 [00:06<00:27,  1.59s/it]
 24%|██▍       | 5/21 [00:07<00:25,  1.59s/it]
 29%|██▊       | 6/21 [00:09<00:24,  1.62s/it]
 33%|███▎      | 7/21 [00:11<00:22,  1.60s/it]
 38%|███▊      | 8/21 [00:12<00:20,  1.60s/it]
 43%|████▎     | 9/21 [00:14<00:19,  1.59s/it]
 48%|████▊     | 10/21 [00:15<00:17,  1.59s/it]
 52%|█████▏    | 11/21 [00:17<00:15,  1.59s/it]
 57%|█████▋    | 12/21 [00:19<00:14,  1.60s/it]
 62%|██████▏   | 13/21 [00:20<00:12,  1.60s/it]
 67%|██████▋   | 14/21 [00:22<00:11,  1.60s/it]
 71%|███████▏  | 15/21 [00:23<00:09,  1.60s/it]
 76%|███████▌  | 16/21 [00:25<00:08,  1.61s/it]
 81%|████████  | 17/21 [00:27<00:06,  1.59s/it]
 86%|████████▌ | 18/21 [00:28<00:04,  1.59s/it]
 90%|█████████ | 19/21 [00:30<00:03,  1.59s/it]
 95%|█████████▌| 20/21 [00:31<00:01,  1.60s/it]
100%|██████████| 21/21 [00:33<00:00,  1.60s/it]
 60%|██████    | 3/5 [01:45<01:09, 34.62s/it]
  0%|          | 0/21 [00:00<?, ?it/s]
  5%|▍         | 1/21 [00:01<00:31,  1.59s/it]
 10%|▉         | 2/21 [00:03<00:30,  1.59s/it]
 14%|█▍        | 3/21 [00:04<00:28,  1.59s/it]
 19%|█▉        | 4/21 [00:06<00:26,  1.59s/it]
 24%|██▍       | 5/21 [00:07<00:25,  1.59s/it]
 29%|██▊       | 6/21 [00:09<00:24,  1.60s/it]
 33%|███▎      | 7/21 [00:11<00:22,  1.59s/it]
 38%|███▊      | 8/21 [00:12<00:20,  1.60s/it]
 43%|████▎     | 9/21 [00:14<00:19,  1.62s/it]
 48%|████▊     | 10/21 [00:15<00:17,  1.60s/it]
 52%|█████▏    | 11/21 [00:17<00:15,  1.59s/it]
 57%|█████▋    | 12/21 [00:19<00:14,  1.59s/it]
 62%|██████▏   | 13/21 [00:20<00:12,  1.59s/it]
 67%|██████▋   | 14/21 [00:22<00:11,  1.59s/it]
 71%|███████▏  | 15/21 [00:23<00:09,  1.60s/it]
 76%|███████▌  | 16/21 [00:25<00:07,  1.59s/it]
 81%|████████  | 17/21 [00:27<00:06,  1.60s/it]
 86%|████████▌ | 18/21 [00:28<00:04,  1.59s/it]
 90%|█████████ | 19/21 [00:30<00:03,  1.60s/it]
 95%|█████████▌| 20/21 [00:31<00:01,  1.59s/it]
100%|██████████| 21/21 [00:33<00:00,  1.60s/it]
 80%|████████  | 4/5 [02:19<00:34, 34.24s/it]
  0%|          | 0/21 [00:00<?, ?it/s]
  5%|▍         | 1/21 [00:01<00:31,  1.58s/it]
 10%|▉         | 2/21 [00:03<00:30,  1.58s/it]
 14%|█▍        | 3/21 [00:04<00:28,  1.58s/it]
 19%|█▉        | 4/21 [00:06<00:27,  1.59s/it]
 24%|██▍       | 5/21 [00:07<00:25,  1.58s/it]
 29%|██▊       | 6/21 [00:09<00:23,  1.60s/it]
 33%|███▎      | 7/21 [00:11<00:22,  1.60s/it]
 38%|███▊      | 8/21 [00:12<00:21,  1.63s/it]
 43%|████▎     | 9/21 [00:14<00:19,  1.62s/it]
 48%|████▊     | 10/21 [00:16<00:17,  1.61s/it]
 52%|█████▏    | 11/21 [00:17<00:16,  1.63s/it]
 57%|█████▋    | 12/21 [00:19<00:14,  1.65s/it]
 62%|██████▏   | 13/21 [00:21<00:13,  1.66s/it]
 67%|██████▋   | 14/21 [00:22<00:11,  1.65s/it]
 71%|███████▏  | 15/21 [00:24<00:09,  1.66s/it]
 76%|███████▌  | 16/21 [00:26<00:08,  1.67s/it]
 81%|████████  | 17/21 [00:27<00:06,  1.65s/it]
 86%|████████▌ | 18/21 [00:29<00:04,  1.64s/it]
 90%|█████████ | 19/21 [00:30<00:03,  1.64s/it]
 95%|█████████▌| 20/21 [00:32<00:01,  1.62s/it]
100%|██████████| 21/21 [00:34<00:00,  1.63s/it]
100%|██████████| 5/5 [02:53<00:00, 34.76s/it]

In [59]:
fs.ls('gs://arc-scbasecount/2025-02-25/metadata/')

['arc-scbasecount/2025-02-25/metadata/Gene',
 'arc-scbasecount/2025-02-25/metadata/GeneFull',
 'arc-scbasecount/2025-02-25/metadata/GeneFull_Ex50pAS',
 'arc-scbasecount/2025-02-25/metadata/GeneFull_ExonOverIntron',
 'arc-scbasecount/2025-02-25/metadata/Velocyto']

In [195]:
with fs.open('gs://arc-scbasecount/2025-02-25/metadata/GeneFull/Homo_sapiens/sample_metadata.parquet', 'rb') as f:
    df = pd.read_parquet(f)

In [196]:
df

,entrez_id,srx_accession,feature_type,file_path,obs_count,lib_prep,tech_10x,cell_prep,organism,tissue,disease,perturbation,cell_line,czi_collection_id,czi_collection_name
0,33064764,SRX24745422,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,21004,10x_Genomics,multiome,single_cell,Homo sapiens,eye,unsure,unsure,unsure,None,None
1,29539783,ERX10335127,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,3899,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,heart,normal,PD0325901 (MEK inhibitor),H9,None,None
2,26040869,ERX10019098,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,10657,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,brain,Parkinson's disease,none,EDi001-B,None,None
3,29309592,ERX10671983,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,1343,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,brain,normal,none,H1-hESC,None,None
4,26040862,ERX10019091,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,13367,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,brain,Parkinson's Disease,none,WTSIi018-B-1,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16072,33213945,SRX24879311,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,44532,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,other,"mental health disparities, sexual minorities",impact of neighborhood cohesion on mental health,not applicable,None,None
16073,35673845,SRX26414993,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,24233,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,other,none specified,"WNT, BMP, and VEGF signaling modulation",hiPSCs (WTC WT background/RRID: CVCL_Y803),None,None
16074,28994714,SRX21511129,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,101162,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,immune system,"hair loss, androgenetic alopecia",Cas9 genome edited T cells,Dermal papilla cells,None,None
16075,22158384,SRX15560537,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,81043,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,bone marrow,chronic myelogenous leukemia,CRISPRi genetic screens,K562,None,None
16076,25859288,SRX18774274,GeneFull,gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/...,87778,10x_Genomics,3_prime_gex,single_cell,Homo sapiens,other,unsure,3 hours LPS,Cas9-expressing THP-1,None,None

In [200]:
fs.ls('gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens')

['arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019090.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019091.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019092.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019093.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019094.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019095.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019096.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019097.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019098.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10019099.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10023320.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10023321.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10023323.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10023324.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10023326.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10128379.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10128380.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10128381.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10299500.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10299501.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10299503.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10299504.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10299505.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10299506.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10299507.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10299508.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10300685.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10300686.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10300687.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10300688.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10300690.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10300704.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10300706.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10328896.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10328897.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10335124.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10335125.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10335127.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10388089.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10388090.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404943.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404944.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404947.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404948.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404950.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404951.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404953.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404954.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404955.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404956.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404957.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404958.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404959.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404960.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404961.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404962.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404963.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404964.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10404966.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10630898.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10630902.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10671981.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10671983.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10671984.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10671985.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10671986.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10855739.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10855740.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10855741.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10855742.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10855743.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10855744.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10956699.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10956700.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10970987.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10975666.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10975667.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10975668.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10975669.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10975670.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10975671.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10975674.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10984430.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10984431.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10984432.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10984433.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10984434.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10984435.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10984442.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10984446.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987142.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987143.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987144.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987145.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987146.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987147.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987148.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987149.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987150.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987151.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987152.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987153.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987159.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987160.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987161.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987162.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987163.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987164.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987165.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987166.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987167.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987168.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987169.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987170.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987171.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987172.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987173.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987174.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987175.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987176.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987177.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987178.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987179.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987180.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987181.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987182.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987183.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987184.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987185.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987186.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987187.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987188.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987189.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987190.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987196.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987199.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987200.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987201.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987203.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987204.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987205.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987206.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987207.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987208.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987209.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987210.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987211.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987212.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987213.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987215.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987216.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987217.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987219.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987220.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987221.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987222.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987223.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987224.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987225.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987226.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10987227.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10991172.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX10991175.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11034008.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11034009.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11036829.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11036830.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11036831.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059478.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059479.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059480.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059481.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059482.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059483.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059484.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059485.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059486.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059487.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059488.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059489.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059490.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059491.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059492.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059493.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059494.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059495.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059497.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059498.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059499.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059501.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11059502.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146191.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146193.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146194.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146197.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146198.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146199.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146200.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146201.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146202.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146203.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146204.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146205.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146206.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146207.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146208.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146210.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146211.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146215.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146216.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146218.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146219.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146220.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146221.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146222.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146223.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146224.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146225.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146226.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146227.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146228.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146229.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146230.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146231.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146235.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146236.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146237.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146238.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146239.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146240.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11146241.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148723.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148724.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148725.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148726.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148727.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148728.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148729.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148730.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148732.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148733.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148734.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148735.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148736.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148737.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148738.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148739.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148740.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148741.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148743.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148744.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148745.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148746.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148747.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148748.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148749.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148750.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148751.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148752.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148753.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148754.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148755.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148756.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148757.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148758.h5ad',
 'arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/ERX11148759.h5ad',

In [202]:
with fs.open('gs://arc-scbasecount/2025-02-25/h5ad/GeneFull/Homo_sapiens/SRX26414993.h5ad', 'rb') as f:
    adata = sc.read_h5ad(f)

In [207]:
adata.obs#['SRX_accession']#.unique()

                  gene_count  umi_count SRX_accession
AAACCCAAGCAATAAC        5999    18036.0   SRX26414993
AAACCCAAGCACTCAT         575     2207.0   SRX26414993
AAACCCAAGCCGCTTG        5555    16342.0   SRX26414993
AAACCCAAGCCTGGAA        7003    30612.0   SRX26414993
AAACCCAAGGAGACCT        7119    28252.0   SRX26414993
...                      ...        ...           ...
TTTGTTGTCCGCGAGT        5966    21870.0   SRX26414993
TTTGTTGTCGAGTCTA        5747    22230.0   SRX26414993
TTTGTTGTCGTCGACG        6492    24723.0   SRX26414993
TTTGTTGTCTCTAAGG        7129    32126.0   SRX26414993
TTTGTTGTCTTGAGCA        5766    16330.0   SRX26414993

[24233 rows x 3 columns]

In [209]:
adata.var

                gene_symbols    feature_types
ENSG00000243485  MIR1302-2HG  Gene Expression
ENSG00000237613      FAM138A  Gene Expression
ENSG00000186092        OR4F5  Gene Expression
ENSG00000238009   AL627309.1  Gene Expression
ENSG00000239945   AL627309.3  Gene Expression
...                      ...              ...
ENSG00000277836   AC141272.1  Gene Expression
ENSG00000278633   AC023491.2  Gene Expression
ENSG00000276017   AC007325.1  Gene Expression
ENSG00000278817   AC007325.4  Gene Expression
ENSG00000277196   AC007325.2  Gene Expression

[36601 rows x 2 columns]

In [188]:
df[df['srx_accession'].str.startswith('SRX71') & (df['srx_accession'].str.len()  == 10)]['srx_accession']

3793    SRX7117646
3819    SRX7117650
3820    SRX7117648
Name: srx_accession, dtype: object

In [30]:
with fs.open('gs://arc-scbasecount/2025-02-25/metadata/GeneFull/Homo_sapiens/obs_metadata.parquet', 'rb') as f:
    df_ = pd.read_parquet(f)

In [31]:
df_

           gene_count  umi_count SRX_accession      cell_barcode
0                 440     1134.0   SRX15405020  AAACCCAAGTAGAATC
1                5311    17996.0   SRX15405020  AAACCCACAACCAATC
2                5683    21854.0   SRX15405020  AAACCCACAACGACAG
3                5806    26976.0   SRX15405020  AAACCCACATGTGGCC
4                1600     2802.0   SRX15405020  AAACCCAGTGATGGCA
...               ...        ...           ...               ...
119038714         646     1015.0   SRX18761311  TTTGTTGCAGATTAAG
119038715         414      552.0   SRX18761311  TTTGTTGCATGAGAAT
119038716        6080    19703.0   SRX18761311  TTTGTTGGTCATAACC
119038717        2206     6719.0   SRX18761311  TTTGTTGTCCATTCAT
119038718        3560     8140.0   SRX18761311  TTTGTTGTCCGGACGT

[119038719 rows x 4 columns]