In [1]:
import scanpy as sc
import pandas as pd
import anndata
import re
from tqdm import tqdm

In [2]:
file1 = '/lustre/groups/ml01/workspace/manuel.gander/data/prelimma/sciplex/'

In [3]:
adata = sc.read_h5ad('/lustre/groups/ml01/workspace/manuel.gander/sciplex/bulked.h5ad')

/home/icb/manuel.gander/miniconda3/envs/seacells/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [4]:
celllines = sorted(set(adata.obs.cell_name))

In [5]:
for cellline in celllines:
    ads = adata[adata.obs['cell_name']==cellline].copy()
    print(cellline)
    
    vc = ads.obs[['drugname_drugconc', 'n_cells']].groupby('drugname_drugconc').sum()
    c_kept = vc[vc.n_cells>50].index.values
    adss = ads[ads.obs.drugname_drugconc.isin(c_kept)].copy()
    break
    
    #a0 = ads.obs['plate'].astype('str').values
    #a1 = ads.obs['drugname_drugconc'].astype('str').values
    #ads.obs['drugname_drugconc'] = [a+'_'+b if b!="control_0.0" else b for a,b in zip(a0,a1)]
    
    pd.DataFrame(adss.X).to_csv(file1+cellline+"_X.csv", index=False)
    adss.var.to_csv(file1+cellline+"_var.csv")
    adss.obs.to_csv(file1+cellline+"_obs.csv")

A549

/home/icb/manuel.gander/miniconda3/envs/seacells/lib/python3.8/site-packages/anndata/_core/anndata.py:1840: UserWarning: Variable names are not unique. To make them unique, call `.var_names_make_unique`.
  utils.warn_names_duplicates("var")

In [23]:
adss.var

                            ensembl_id   ncounts  ncells
ensembl_id
id gene_short_name  id gene_short_name   26582.0   23228
ENSG00000000003        ENSG00000000003      35.0      33
ENSG00000000005        ENSG00000000005  163109.0  116153
ENSG00000000419        ENSG00000000419   49655.0   41883
ENSG00000000457        ENSG00000000457   57943.0   49609
...                                ...       ...     ...
ENSMUSG00000114964  ENSMUSG00000114964       0.0       0
ENSMUSG00000114965  ENSMUSG00000114965       1.0       1
ENSMUSG00000114966  ENSMUSG00000114966       0.0       0
ENSMUSG00000114967  ENSMUSG00000114967       0.0       0
ENSMUSG00000114968  ENSMUSG00000114968       0.0       0

[110984 rows x 3 columns]

In [14]:
adata.var

                            ensembl_id   ncounts  ncells
ensembl_id
id gene_short_name  id gene_short_name   26582.0   23228
ENSG00000000003        ENSG00000000003      35.0      33
ENSG00000000005        ENSG00000000005  163109.0  116153
ENSG00000000419        ENSG00000000419   49655.0   41883
ENSG00000000457        ENSG00000000457   57943.0   49609
...                                ...       ...     ...
ENSMUSG00000114964  ENSMUSG00000114964       0.0       0
ENSMUSG00000114965  ENSMUSG00000114965       1.0       1
ENSMUSG00000114966  ENSMUSG00000114966       0.0       0
ENSMUSG00000114967  ENSMUSG00000114967       0.0       0
ENSMUSG00000114968  ENSMUSG00000114968       0.0       0

[110984 rows x 3 columns]