# Format of pseudobulk output file

In [1]:
print(1)

1

In [2]:
import anndata as ad
import pandas as pd

In [3]:
pd.options.display.max_columns = 30

The output file from the pseudobulking pipeline is an **anndata** object containing **obs**, **var** annotations and sparse count matrix **.X** and the dictionary-like object **layers**.

# Sci-Plex

In [4]:
adata = ad.read_h5ad('../data/sciplex/pseudobulk/subsample/srivatsan20_sciplex3_subsample.h5ad')

The example output for the Sci-plex subsample dataset:

In [5]:
adata

AnnData object with n_obs × n_vars = 1459 × 58302
    obs: 'plate', 'well', 'cell_type', 'perturbagen', 'pert_type', 'is_control', 'pert_dose_uM', 'pert_time_h', 'suspension_type', 'tissue', 'tissue_type', 'disease', 'library', 'stimulation', 'guide', 'dataset', 'assay', 'development_stage', 'organism', 'sex', 'self_reported_ethnicity', 'pubchem_cid', 'psbulk_cells', 'psbulk_counts'
    var: 'symbol'
    layers: 'psbulk_props'

## .obs

### columns:

The .obs annotation has 24 columns:

In [6]:
adata.obs.columns

Index(['plate', 'well', 'cell_type', 'perturbagen', 'pert_type', 'is_control',
       'pert_dose_uM', 'pert_time_h', 'suspension_type', 'tissue',
       'tissue_type', 'disease', 'library', 'stimulation', 'guide', 'dataset',
       'assay', 'development_stage', 'organism', 'sex',
       'self_reported_ethnicity', 'pubchem_cid', 'psbulk_cells',
       'psbulk_counts'],
      dtype='object')

In [7]:
adata.obs.dtypes

plate                      category
well                       category
cell_type                  category
perturbagen                category
pert_type                  category
is_control                 category
pert_dose_uM                float64
pert_time_h                 float64
suspension_type            category
tissue                     category
tissue_type                category
disease                    category
library                    category
stimulation                category
guide                      category
dataset                    category
assay                      category
development_stage          category
organism                   category
sex                        category
self_reported_ethnicity    category
pubchem_cid                category
psbulk_cells                  int64
psbulk_counts                 int64
dtype: object

In [8]:
adata.obs

,plate,well,cell_type,perturbagen,pert_type,is_control,pert_dose_uM,pert_time_h,suspension_type,tissue,tissue_type,disease,library,stimulation,guide,dataset,assay,development_stage,organism,sex,self_reported_ethnicity,pubchem_cid,psbulk_cells,psbulk_counts
sample_id,,,,,,,,,,,,,,,,,,,,,,,,
plate10_plate4_C7_panobinostat_CVCL_0023,plate10,plate4_C7,CVCL_0023,panobinostat,compound,False,0.01,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,6918837,1,832
plate10_plate4_H12_PCI-34051_CVCL_0023,plate10,plate4_H12,CVCL_0023,PCI-34051,compound,False,0.01,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,24753719,1,746
plate11_plate5_B12_A-366_CVCL_0023,plate11,plate5_B12,CVCL_0023,A-366,compound,False,1.00,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,76285486,1,704
plate11_plate5_B8_AR-42_CVCL_0023,plate11,plate5_B8,CVCL_0023,AR-42,compound,False,1.00,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,6918848,1,1110
plate11_plate5_B9_AMG-900_CVCL_0023,plate11,plate5_B9,CVCL_0023,AMG-900,compound,False,1.00,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,24856041,1,1283
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
plate9_plate3_A4_tazemetostat_CVCL_0023,plate9,plate3_A4,CVCL_0023,tazemetostat,compound,False,10.00,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,66558664,1,755
plate9_plate3_A7_SRT2104_CVCL_0023,plate9,plate3_A7,CVCL_0023,SRT2104,compound,False,1.00,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,25108829,1,1169
plate9_plate3_F1_Divalproex_CVCL_0023,plate9,plate3_F1,CVCL_0023,Divalproex,compound,False,10.00,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,23663956,1,2164
plate9_plate3_F5_Aurora_CVCL_0023,plate9,plate3_F5,CVCL_0023,Aurora,compound,False,10.00,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,86222,1,1298
plate9_plate3_H7_ITSA-1_CVCL_0023,plate9,plate3_H7,CVCL_0023,ITSA-1,compound,False,1.00,24.0,nucleus,lung,cell culture,lung adenocarcinoma,NaN,NaN,NaN,srivatsan20_sciplex3,sci-Plex,unknown,human,male,European,771910,1,735

**NB!** The standardization/validation is performed by using `bionty==1.5.0` and `wetlab==1.2.0` for **Tahoe**, and `bionty==1.0.0` and `wetlab==1.0.0` for **Sciplex**. The config files with the default database versions (the latest in the config) used for the standardization are located: [bionty==1.0.0](https://github.com/laminlabs/bionty/blob/1.0.0/bionty/base/sources.yaml), [bionty==1.5.0](https://github.com/laminlabs/bionty/blob/1.5.0/bionty/base/sources.yaml))

`plate <category>` - is a column which indicates the experimental plate, which was used to perform perturbation; it is written in the format `platei`. **NB!** Make sure that cells in this column do only contain letters and digits (or `.` in the worst case).

`well <category>` - is a column which indicates the id of the well on the experimental plate, where the perturbation was performed; the format might vary, but we tried to stick to letter-number annotation, e.g. `A9`.

`cell_type <category>` - is a column indicating a cell type used in the experiments, cellosaurus ids are used to identify the cancer cell line. No the specific version of the **Cellosaurus** database is used.

`perturbagen <category>` - indicates the name of perturbagen. They are taken from the initial datasets and standardized by the lamin lab using `chebi` with the version `2024-07-27` for both **Sci-Plex** and **Tahoe**.

`pert_type <category>` - indicates the type of perturbagen (e.g. `compound`, `genetic`, `biologic`, `physical`: [docs for `wetlab==1.0.0`](https://github.com/laminlabs/wetlab/blob/1.0.0/docs/guide/pert-curator.ipynb)). The types are standardized by lamin lab.

`is_control <bool>` - indicates if the perturbation is control or not. (Currently, if the perturbagen is `DMSO` - then perturbation is control)

`pert_dose_uM <float64>` - the information on the concentration, which is converted to standard units (uM) by the python package `magnitude==1.1.2`.

`pert_time_h <float64>` - the information on the perturbation duration, which is converted to standard units (hours) by the python package `magnitude==1.1.2`.

`suspension_type <category>` - what kind of biological material was dissociated into single cells or nuclei, manually annotated by the lamin lab.

`tissue <category>` - the information on the tissue related to the cell line, manually annotated by the lamin lab; validated with (`uberon 2024-08-07`). 

`tissue_type <category>` - the information on the tissue type related to the cell line (e.g. `cell culture`), manually annotated by the lamin lab. There are pipelines for cell line annotations (`suspension_type`, `tissue`, `tissue_type`, `assay`) : [**Sci-Plex**](https://lamin.ai/laminlabs/pertdata/transform/qNq33VZmhe4t0000/fGwen5GH3Zixpehg8iaN), [**Tahoe**](https://lamin.ai/laminlabs/pertdata/transform/MQDTES9N9RCl0000).

`disease <category>` - indicates the name of disease (the type of tumor) related to the cell line, standardized by the lamin lab. For both **Sci-Plex** and **Tahoe**: `mondo` with `2024-08-06` version, `doid` with `2024-05-29` version.

`library <category>` - indicates the ID of the library which is used to perform sequencing; in some cases the info might not exist.

`stimulation <category>` - information on the stimuli, additional conditions which cells are exposed to during the perturbation; in some cases the info might not exist.

`guide <category>` - relevant to the genetic perturbations (e.g. for CRISPR-based ones it determines a guide RNA directs the CRISPR system); in some cases the info might not exist.

`dataset <category>` - a name of the dataset, specified manually. There is no specific format.

`assay <category>` - the info on the experimental method used to capture the information for the construction the dataset, manually annotated by the lamiin lab, both datasets were validated with `efo 3.70.0`.

`development_stage <category>` - the stage of the development of the tissue from the patient, might include age (e.g. `51-year-old stage`, or `unknown`). It was standardized and validated by the lamin lab (the db for validation for both datasets: `hsapdv 2024-05-28`).

`organism <category>` - a type of an organism, which cell line is used for the perturbation experiment, we consider `human` cells. It was standardized and validated by the lamin lab (the db for validation for both datasets: `ensembl release 112`).

`sex <category>` - a gender of an organism, which cell line is used for the perturbation experiment. It is specified manually by the lamin lab, validated with `pato 2024-03-28`.

`self_reported_ethnicity <category>` - an ethnicity of a human, which cell line is used for the perturbation experiment. It is specified manually by the lamin lab, validated with `hancestro 3.0` for **Sci-Plex** and `hancestro 2025-04-01` for **Tahoe**. There are pipelines for patient annotations (`development_stage`, `organism`, `sex`, `self_reported_ethnicity`) : [Sci-Plex](https://lamin.ai/laminlabs/pertdata/transform/qNq33VZmhe4t0000/fGwen5GH3Zixpehg8iaN), [Tahoe](https://lamin.ai/laminlabs/pertdata/transform/dtQBk1ocZHdN0001/6I5be4yXJPdDSyeh).

`pubchem_cid <category>` - the **PubChem** CIDs retrieved by using the python package `pubchempy==1.0.5`.

`psbulk_cells <int64>` - the number of cells which are included in pseudobulk (obtained by using `.pp.pseudobulk` function from the `decoupler==2.1.0`).

`psbulk_counts <int64>` - the number of counts which are included in pseudobulk (obtained by using `.pp.pseudobulk` function from the `decoupler==2.1.0`).

### index:

The index `sample_id <object>` for pseudobulk is constructed as `plate` + '\_' + `well` + '\_' + `perturbagen` + '\_' + `cell_type`

## .var

### columns:

.var includes one column: `symbol`

`symbol <category>` - mainly the human gene symbol from HGNC database, but also other ids from the original datasets might be used (e.g. `AC015801.1`).

In [9]:
adata.var.columns

Index(['symbol'], dtype='object')

In [10]:
adata.var.dtypes

symbol    category
dtype: object

In [11]:
adata.var

                     symbol
ensembl_id
ENSG00000229258  AL445488.1
ENSG00000214702  AC010931.1
ENSG00000242855   RN7SL496P
ENSG00000145103       ILDR1
ENSG00000243770    RN7SL65P
...                     ...
ENSG00000198915    RASGEF1A
ENSG00000184388   PABPC1L2B
ENSG00000230836   LINC01293
ENSG00000243964   RPL23AP65
ENSG00000267376  AC015801.1

[58302 rows x 1 columns]

### index:

The index `ensembl_id <object>` for **.var** is constructed as ID from **Ensemble** database. For [Sci-plex](https://lamin.ai/laminlabs/pertdata/transform/qNq33VZmhe4t0000) validation the default (`release-112`) version is used but as it is [found](https://github.com/theislab/op3_v2/blob/slurm_scripts_notebooks/draft_notebooks/a_trial_to_find_release_of_ensembl_for_sciplex.ipynb) the probable ensembl releases are `90` or `91`; for [Tahoe](https://lamin.ai/laminlabs/pertdata/transform/OlAaeZKlSyri0000/0LF29cNOvRPwM3Is) the `release-109` version is used.

## .X

In [12]:
adata.X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 2457641 stored elements and shape (1459, 58302)>

The `.X` object is a sparse matrix which contain pseudobulk-aggregated integer counts.

## layers

In [13]:
adata.layers

Layers with keys: psbulk_props

In [14]:
adata.layers['psbulk_props']

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 2457641 stored elements and shape (1459, 58302)>

The `.layers['psbulk_props']` object is a sparse matrix which contain information about the proportion of cells that have a non-zero value for a given feature (obtained by using `.pp.pseudobulk` function from the `decoupler==2.1.0`). I do not think it is 100% necessary information, so it could be ommitted, if it is impossible to receive.

# Tahoe

In [15]:
adata = ad.read_h5ad('../data/tahoe/pseudobulk/subsample/tahoe_subsample.h5ad')

In [16]:
adata

AnnData object with n_obs × n_vars = 36266 × 62710
    obs: 'plate', 'well', 'cell_type', 'perturbagen', 'pert_type', 'is_control', 'pert_dose_uM', 'pert_time_h', 'suspension_type', 'tissue', 'tissue_type', 'disease', 'library', 'stimulation', 'guide', 'dataset', 'assay', 'development_stage', 'organism', 'sex', 'self_reported_ethnicity', 'pubchem_cid', 'psbulk_cells', 'psbulk_counts'
    var: 'symbol'
    layers: 'psbulk_props'

## .obs

In [17]:
adata.obs.columns

Index(['plate', 'well', 'cell_type', 'perturbagen', 'pert_type', 'is_control',
       'pert_dose_uM', 'pert_time_h', 'suspension_type', 'tissue',
       'tissue_type', 'disease', 'library', 'stimulation', 'guide', 'dataset',
       'assay', 'development_stage', 'organism', 'sex',
       'self_reported_ethnicity', 'pubchem_cid', 'psbulk_cells',
       'psbulk_counts'],
      dtype='object')

In [18]:
adata.obs.dtypes

plate                      category
well                       category
cell_type                  category
perturbagen                category
pert_type                  category
is_control                 category
pert_dose_uM                float64
pert_time_h                 float64
suspension_type            category
tissue                     category
tissue_type                category
disease                    category
library                    category
stimulation                category
guide                      category
dataset                    category
assay                      category
development_stage          category
organism                   category
sex                        category
self_reported_ethnicity    category
pubchem_cid                category
psbulk_cells                  int64
psbulk_counts                 int64
dtype: object

In [19]:
adata.obs

,plate,well,cell_type,perturbagen,pert_type,is_control,pert_dose_uM,pert_time_h,suspension_type,tissue,tissue_type,disease,library,stimulation,guide,dataset,assay,development_stage,organism,sex,self_reported_ethnicity,pubchem_cid,psbulk_cells,psbulk_counts
sample_id,,,,,,,,,,,,,,,,,,,,,,,,
plate6_A10_Palmatine (chloride)_CVCL_0023,plate6,A10,CVCL_0023,Palmatine (chloride),compound,False,5.00,24.0,cell,lung,cell culture,carcinoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,58-year-old stage,human,male,European,73442,1,961
plate6_A10_Palmatine (chloride)_CVCL_0069,plate6,A10,CVCL_0069,Palmatine (chloride),compound,False,5.00,24.0,cell,skin of body,cell culture,melanoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,60-year-old stage,human,male,European,73442,1,2006
plate6_A10_Palmatine (chloride)_CVCL_0099,plate6,A10,CVCL_0099,Palmatine (chloride),compound,False,5.00,24.0,cell,stomach,cell culture,adenocarcinoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,44-year-old stage,human,male,East Asian,73442,1,1084
plate6_A10_Palmatine (chloride)_CVCL_0131,plate6,A10,CVCL_0131,Palmatine (chloride),compound,False,5.00,24.0,cell,brain,cell culture,glioblastoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,53-year-old stage,human,male,European,73442,3,8457
plate6_A10_Palmatine (chloride)_CVCL_0179,plate6,A10,CVCL_0179,Palmatine (chloride),compound,False,5.00,24.0,cell,breast,cell culture,invasive carcinoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,60-year-old stage,human,female,European,73442,2,4838
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
plate13_H9_Edoxaban (tosylate monohydrate)_CVCL_1693,plate13,H9,CVCL_1693,Edoxaban (tosylate monohydrate),compound,False,0.05,24.0,cell,lung,cell culture,small cell carcinoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,54-year-old stage,human,male,European,25022378,3,6109
plate13_H9_Edoxaban (tosylate monohydrate)_CVCL_1716,plate13,H9,CVCL_1716,Edoxaban (tosylate monohydrate),compound,False,0.05,24.0,cell,lung,cell culture,small cell carcinoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,69-year-old stage,human,male,European,25022378,1,3601
plate13_H9_Edoxaban (tosylate monohydrate)_CVCL_1717,plate13,H9,CVCL_1717,Edoxaban (tosylate monohydrate),compound,False,0.05,24.0,cell,colon,cell culture,adenocarcinoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,53-year-old stage,human,female,European,25022378,2,12491
plate13_H9_Edoxaban (tosylate monohydrate)_CVCL_1724,plate13,H9,CVCL_1724,Edoxaban (tosylate monohydrate),compound,False,0.05,24.0,cell,colon,cell culture,adenocarcinoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,83-year-old stage,human,female,European,25022378,1,1637
plate13_H9_Edoxaban (tosylate monohydrate)_CVCL_1731,plate13,H9,CVCL_1731,Edoxaban (tosylate monohydrate),compound,False,0.05,24.0,cell,lung,cell culture,squamous cell carcinoma,NaN,NaN,NaN,tahoe100,Parse Evercode Whole Transcriptome v3,53-year-old stage,human,male,European,25022378,1,1886

## .var

In [20]:
adata.var.columns

Index(['symbol'], dtype='object')

In [21]:
adata.var.dtypes

symbol    category
dtype: object

In [22]:
adata.var

                    symbol
ensembl_id
ENSG00000214872     SMTNL1
ENSG00000277595        NaN
ENSG00000133026      MYH10
ENSG00000250302  LINC01618
ENSG00000218337        NaN
...                    ...
ENSG00000202074  RNU6-715P
ENSG00000189337       KAZN
ENSG00000234380  LINC01426
ENSG00000251890  RNA5SP497
ENSG00000288123     OR4G6P

[62710 rows x 1 columns]

## .X

In [23]:
adata.X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 82237019 stored elements and shape (36266, 62710)>

## layers

In [24]:
adata.layers

Layers with keys: psbulk_props

In [25]:
adata.layers['psbulk_props']

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 82237019 stored elements and shape (36266, 62710)>

## bionity sources

In [26]:
bio_100 = pd.read_csv('./bionty.1.0.0.used_sources.csv')

In [27]:
#bionty==1.0.0
bio_100

                entity                  organism      source      version
0             Organism               vertebrates     ensembl  release-112
1             Organism                  bacteria     ensembl   release-57
2             Organism                     fungi     ensembl   release-57
3             Organism                   metazoa     ensembl   release-57
4             Organism                    plants     ensembl   release-57
5             Organism                       all   ncbitaxon   2023-06-20
6                 Gene                     human     ensembl  release-112
7                 Gene                     mouse     ensembl  release-112
8                 Gene  saccharomyces cerevisiae     ensembl  release-112
9              Protein                     human     uniprot      2024-03
10             Protein                     mouse     uniprot      2024-03
11          CellMarker                     human  cellmarker          2.0
12          CellMarker                     mouse  cellmarker          2.0
13            CellLine                       all         clo   2022-03-21
14            CellType                       all          cl   2024-08-16
15              Tissue                       all      uberon   2024-08-07
16             Disease                       all       mondo   2024-08-06
17             Disease                     human        doid   2024-05-29
18  ExperimentalFactor                       all         efo       3.70.0
19           Phenotype                     human          hp   2024-04-26
20           Phenotype                 mammalian          mp   2024-06-18
21           Phenotype                 zebrafish          zp   2024-04-18
22           Phenotype                       all        pato   2024-03-28
23             Pathway                       all          go   2024-06-17
24         BFXPipeline                       all       lamin        1.0.0
25                Drug                       all        dron   2024-08-05
26  DevelopmentalStage                     human      hsapdv   2024-05-28
27  DevelopmentalStage                     mouse      mmusdv   2024-05-28
28           Ethnicity                     human   hancestro          3.0
29           BioSample                       all        ncbi      2023-09

In [28]:
bio_150 = pd.read_csv('./bionty.1.5.0.used_sources.csv')

In [29]:
#bionty==1.5.0
bio_150

                entity                  organism        name      version
0             Organism               vertebrates     ensembl  release-112
1             Organism                  bacteria     ensembl   release-57
2             Organism                     fungi     ensembl   release-57
3             Organism                   metazoa     ensembl   release-57
4             Organism                    plants     ensembl   release-57
5             Organism                       all   ncbitaxon   2023-06-20
6                 Gene                     human     ensembl  release-112
7                 Gene                     mouse     ensembl  release-112
8                 Gene  saccharomyces cerevisiae     ensembl  release-112
9              Protein                     human     uniprot      2024-03
10             Protein                     mouse     uniprot      2024-03
11          CellMarker                     human  cellmarker          2.0
12          CellMarker                     mouse  cellmarker          2.0
13            CellLine                       all         clo   2022-03-21
14            CellType                       all          cl   2024-08-16
15              Tissue                       all      uberon   2024-08-07
16             Disease                       all       mondo   2024-08-06
17             Disease                     human        doid   2024-05-29
18  ExperimentalFactor                       all         efo       3.70.0
19           Phenotype                       all        pato   2024-03-28
20           Phenotype                     human          hp   2024-04-26
21           Phenotype                 mammalian          mp   2024-06-18
22           Phenotype                 zebrafish          zp   2024-04-18
23             Pathway                       all          go   2024-06-17
24         BFXPipeline                       all       lamin        1.0.0
25                Drug                       all        dron   2024-08-05
26  DevelopmentalStage                     human      hsapdv   2024-05-28
27  DevelopmentalStage                     mouse      mmusdv   2024-05-28
28           Ethnicity                     human   hancestro   2025-04-01
29           BioSample                       all        ncbi      2023-09